feat(addons) calculating gap width re #8863
icplayer/icplayer pull request #1010
Opened 2023-08-09 12:09 UTC by wkarasSolwit

[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/8863--support--studio-temat--problem-z-d%C5%82ugo%C5%9Bci%C4%85-gap-po-aktualizacji-mau/details?comment=1707573201)
[Wersja testowa](https://test-8663-dot-mauthor-dev.ew.r.appspot.com/mycontent)
[Przykładowa lekcja](https://test-8863-dot-mauthor-dev.ew.r.appspot.com/present/6151398213287936#61)

2023-08-10 06:10 UTC, maciej-zawlocki-solwit requested changes

2023-08-10 06:10 UTC, maciej-zawlocki-solwit commented on src/main/java/com/lorepo/icplayer/client/module/text/GapInfo.java
> +			if (longestAnswerLength < answer.length()) {
to zawsze będzie true, bo nie aktualizujesz longestAnswerLength, tylko longestAnswer.

2023-08-10 06:10 UTC, maciej-zawlocki-solwit commented on src/main/java/com/lorepo/icplayer/client/module/text/TextView.java
> +		var fontSize = '18px';
Co jeśli fontSize jest inny niż 18px?

2023-08-11 07:25 UTC, maciej-zawlocki-solwit approved these changes

2023-08-24 10:18 UTC, maciej-zawlocki-solwit approved these changes

2023-08-25 12:05 UTC, msawoniuk approved these changes

2023-08-25 12:05 UTC, merged