Added play, pause and stop commands to Flash Cards, re #8817
icplayer/icplayer pull request #1015
Opened 2023-08-24 08:10 UTC by maciej-zawlocki-solwit

ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8817
wersja testowa: https://test-8817-dot-mauthor-dev.ew.r.appspot.com/

2023-08-24 09:22 UTC, msawoniuk approved these changes

2023-09-04 07:55 UTC, wkarasSolwit submitted a review, later dismissed
OK

2023-09-13 13:07 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +        var originalCard = presenter.state.currentCard;
Czy nie powinna to być zmienna globalna w presenter ? Obecnie chyba nic nie robi

2023-09-13 13:07 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +        if ((presenter.isFrontPlaying || presenter.isBackPlaying) && presenter.state.currentCard != originalCard) {
"presenter.state.currentCard != originalCard" czy nie jest zawsze true ? 
Spójrz na mój poniższy komentarz

2023-09-13 13:16 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +                var audioSrc = card.AudioFront;
Lepsze podejście:
var audioSrc = reverse ? card.AudioBack : card.AudioFront;

2023-09-13 13:36 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +    presenter.play = function(cardIndex = -1, reverse = false) {
Czy nie będzie to powodować błędów dla addonów z większą liczbą kard niż 9 ?

2023-09-13 13:38 UTC, msawoniuk requested changes
Proszę się odpowiednio odnieść do komentarzy oraz zaznaczonych linii

1. Analogicznie do 'Gdy jestem na karcie 2 i uruchamiam komendę play z karty 1 to idzie item: "2", value: "playing" - powinno być item: "1"' powinno także działać stop i pause.
Obecnie gdy jestem na karcie 2 i uruchomię komendę "play(1, false)" to przy użyciu komendy "stop()" na karcie numer 2 to otrzymam "{source: 'FlashCards1', item: '2', value: 'ended', score: '', pageId: '', …}" zamiast "{source: 'FlashCards1', item: '1', value: 'ended', score: '', pageId: '', …}"
Lekcja: https://test-8817-dot-mauthor-dev.ew.r.appspot.com/present/5851568895164416

2. Jak aktywować poprawnie play przez np. Single State button patrz: https://test-8817-dot-mauthor-dev.ew.r.appspot.com/present/5851568895164416#2

2023-09-18 06:41 UTC, maciej-zawlocki-solwit commented on addons/FlashCards/src/presenter.js
>      presenter.nextCard = function (disregardNoLoop) {
zapętlanie zależy od wartości property disable loop

2023-10-11 08:52 UTC, maciej-zawlocki-solwit commented
Odnośnie 2, dodałem możliwość przekazania string zamiast boolean w reverse (info w dokumentacji).

2023-10-11 11:09 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
>      presenter.nextCard = function (disregardNoLoop) {
Podałem wcześniej złą stronę lekcji: https://mauthor-dev.ew.r.appspot.com/present/6042549682700288
Nadal to zjawisko występuje. I tak jak napisałem nie jest to związane w Twymi zmianami. Dziś utworzę na to osobne zadanie.

2023-10-11 11:16 UTC, msawoniuk reviewed
Zostało mi kilka testów manualnych z komendami. Po stronie kodu wszystko jest OK.

2023-10-11 15:09 UTC, msawoniuk approved these changes
Co do kodu nie mam zastrzeżeń. 
Nadal pozostaje kwestia eventu z mojego poprzedniego CR (punkt 1). 
Decyzję odnośnie tego zostawiłem osobie zajmującej się testami akceptacyjnymi

2023-10-16 10:12 UTC, msawoniuk approved these changes

2023-10-18 08:49 UTC, msawoniuk requested changes
1. Podczas testów napotkałem błąd, który opisałem w jednym z komentarzy.
2. Myślę, że jest to błędne zachowanie. 
Za pomocą komendy można uruchomić audio z innej karty, bądź strony. Jeżeli jesteśmy na karcie 1, przód i uruchomimy komendę do odtworzenia nagrania z karty 2, przód to nagranie będzie lecieć a event "playing" zostanie poprawnie nadane. Jednak w trakcie nagrania można kliknąć guzik karty do odtworzenia obecnego nagrania (czyli z pierwszej strony z przodu). Po kliknięciu zostanie zatrzymane audio obecnie uruchomione, i odtworzy się nagranie z obecnej strony co jest prawidłowe. Jednak nie jest wysyłany event "ended" dla zatrzymania odtwarzania nagrania z karty numer 2. 

W przykładzie wspomniałem o karcie numer 2, jednak to samo jest dla karty numer 1. Wtedy po prostu są po sobie dwa eventy "playing" z "item" równym 1.

3. To samo co w drugim punkcie ale odwrotna sytuacja. Najpierw jest klikany guzik karty a potem wykonywana komenda. W wyniku mamy 2 eventy "playing" i 1 "ended"

Nagrania z odtworzenia błędów wyślę prywatnie

2023-10-18 08:49 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +    presenter.originalCard = -1;
Karta numer 1 jest na początku odkryta, a ta zmienna jest wykorzystywana tylko przy presenter.showCard i presenter.nextCard. Biorąc pod uwagę, że ta zmienna ma śledzić indeksy to presenter.originalCard powinno być równe 1. 

Możliwe, że dla obecnej konfiguracji nie jest to zauważalne bo w presenter.init jest wykonywane presenter.showCard, gdzie presenter.originalCard według kodu jest ustawiane na 1.

Proponuję tą zmianę, aby wartość zgadzała się z początkową wartością presenter.state.currentCard, a tym samym ujednolicając kod.

2023-10-18 08:49 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +        if ((presenter.isFrontPlaying || presenter.isBackPlaying) && presenter.state.currentCard != presenter.originalCard) {
Miałem wątpliwości i przetestowałem na wersji testowej. 

Nie można w tym miejscu wykonywać sendEndedEvent bez przekazania parametru. sendEndedEvent korzysta z wartości presenter.state.currentCard, gdy nie poda się do metody zmiennej. W obecnej sytuacji, gdy gra audio z karty numer 1 i przejdzie się na kartę numer 2 to event "ended" będzie wysyłany wraz z "item": "2", mimo że nagranie z karty numer 1 się kończy, gdyż zaktualizowałeś presenter.state.currentCard zanim wysłałeś event.

Myślę, że albo warunek trzeba dopracować i powinien być sprawdzany na początku metody lub do sendEndedEvent przekazywać presenter.originalCard.

2023-10-18 08:49 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
>              presenter.sendEndedEvent();
biorąc pod uwagę proponowaną zmianę w presenter.nextCard to tutaj też można przekazywać presenter.originalCard

2023-10-30 15:11 UTC, msawoniuk submitted a review, later dismissed

2023-11-03 11:22 UTC, wkarasSolwit submitted a review, later dismissed
OK

2023-11-06 09:37 UTC, wkarasSolwit submitted a review, later dismissed
OK

2023-11-08 12:16 UTC, merged