fix(addons) setting width for gaps re #8925
icplayer/icplayer pull request #1032
Opened 2023-10-04 08:47 UTC by wkarasSolwit

[PR edytor](https://github.com/LearneticSA/iceditor/pull/51)
[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8925)
[Wersja testowa](https://test-8925-dot-mauthor-dev.ew.r.appspot.com)

2023-10-05 10:27 UTC, msawoniuk requested changes
Po Twojej poprawce lekcja klienta z zadania #8905 się psuje. Zobacz lekcje testową https://test-8925-dot-mauthor-dev.ew.r.appspot.com/present/5095405542965248#11 i porównaj ją z mauthor-dev i z widokiem z opisu. Jbc. W 8917 były usuwane style CSS, może ich przywrócenie wystarczy.

Nie wiem czy jest ok z 8909. Nie mnie oceniać. Proponuję, abyś spytał osobę, która tworzyła ticket. Gapy nie są za małe ale min-width jakby nie miało żadnego wpływu.

2023-10-05 10:27 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextView.java
> +	private void setGapWidth(GapWidget gap, int width) {
Proponuję ujednolicić jakie argumenty przyjmuje ta metoda i jej nazwę, względem tej po stronie editora.
Po stronie playera to lepiej aby ta metoda się nazywała setGapMinWidth
Co do argumentów to podkreślę, że warto, jednak nie jest to konieczne.

2023-10-06 06:08 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2023-10-09 07:19 UTC, maciej-zawlocki-solwit approved these changes

2023-10-09 12:25 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2023-10-11 10:39 UTC, maciej-zawlocki-solwit commented on src/main/java/com/lorepo/icplayer/client/module/text/TextView.java
> +import com.lorepo.icf.utils.JavaScriptUtils;
nie będę tylko dla tego dawał declined, ale gdybyś jeszcze musiał coś tu robić to wywal proszę nadmiarowy import.

2023-10-11 10:39 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2023-10-13 09:05 UTC, merged