Added GSA support to Figure Drawing addon
icplayer/icplayer pull request #1070
Opened 2023-12-15 13:57 UTC by maciej-zawlocki-solwit

ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=9003
wersja testowa: https://test-9003-dot-mauthor-dev.ew.r.appspot.com/present/4807859596427264

2023-12-15 15:52 UTC, msawoniuk requested changes
Gdy strona jest reportowalna to są wyświetlane wszystkie linie oraz niektóre migają

2023-12-15 15:52 UTC, msawoniuk commented on addons/FigureDrawing/src/presenter.js
> +    presenter.isGradualShowAnswersActive = false;
Warto byłoby wstawić pustą linię między zmienną a metodą.

2023-12-15 15:52 UTC, msawoniuk commented on addons/FigureDrawing/src/presenter.js
> +            var Lines = presenter.$view.find('.line').not('.nonremovable');
Widzę, że ta metoda została stworzona na podstawie showAnswers. Z tego powodu rozumiem powód braku zmian nazw. Jak będzie potrzeba zmiany w obu miejscach to prosiłbym o zmianę nazwy na `$lines`, ze względu na:
1. Wynikiem jest obiekt jQuerry
2. Zmienna nie powinna zaczynać się z dużej litery

2023-12-27 07:34 UTC, wkarasSolwit submitted a review, later dismissed
OK

2024-01-11 10:28 UTC, maciej-zawlocki-solwit commented
@msawoniuk Daj sobie tutaj approve, bo ja nie mogę w związku z tym że założyłem ten PR.

2024-01-11 10:38 UTC, msawoniuk approved these changes

2024-01-12 08:53 UTC, merged