add(addons) GSA to Line Number, re #9002
icplayer/icplayer pull request #1078
Opened 2024-01-15 07:34 UTC by wkarasSolwit

[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=9002)
[Wersja testowa](https://test-9002-dot-mauthor-dev.ew.r.appspot.com/
[Lekcja](https://test-9002-dot-mauthor-dev.ew.r.appspot.com/present/5275035168145409)

2024-01-15 08:06 UTC, msawoniuk commented on addons/Line_Number/src/presenter.js
> +                addListenerWithTimeout();
Dlaczego nie wewnątrz presenter.gradualShowAnswers ?

2024-01-15 08:52 UTC, msawoniuk commented on addons/Line_Number/src/presenter.js
> +    presenter.addListenerOnHover = function () {
Wydaje mi się, że jeżeli w GSA jest to dodawane to w GHA powinno być usuwane.  Proszę o komentarz

2024-01-15 08:52 UTC, msawoniuk requested changes
Błędy:
1. Gdy strona jest raportowalna to pokazana odpowiedź od razu znika. Objawia się to miganiem, 
2. Odpowiedzi użytkownika znikają po kliknięciu 'x' razu na znak nieskończoności. Kroki do reprodukcji:
A. Zaznacz jakieś punkty
B. Włącz GSA
C. Wyłącz GSA
D. Kliknij kilka razy w znak nieskończoność.
E. Odpowiedzi użytkownika znikneły (ale nie zostały usunięte. Włączenie SA i wyłączenie SA pozwoli na ich ponowne wyświetlenie).
3. Możliwość zaznaczania range w konfiguracji bez range po wystąpieniu przypadku 2. Aby to zrobić kliknij w -nieskończoność a potem nieskończoność. Cały obszar zostanie zaznaczony.

Edit. Też o tym zapominam, jak to widać po moich ostatnich PR-kach jednak proszę, aby dodać link do paczki playera, zgodnie z nowymi ustaleniami.

2024-01-15 13:17 UTC, wkarasSolwit commented on addons/Line_Number/src/presenter.js
> +                addListenerWithTimeout();
ponieważ listener jest tracony na każdym addonie Line Number

2024-01-17 08:08 UTC, maciej-zawlocki-solwit approved these changes

2024-01-19 12:09 UTC, merged