feat(addons): add displaying next or previous page in ANB, re #9054
icplayer/icplayer pull request #1099
Opened 2024-02-06 10:09 UTC by wkarasSolwit

[Ticket](https://app.assembla.com/spaces/lorepo/tickets/9054-anb-%E2%80%93%C2%A0poprawka-widocznych-przycisk%C3%B3w-(paginacji)/details)
[Wersja testowa](https://test-9054-dot-mauthor-dev.ew.r.appspot.com)
[Lekcja](https://test-9054-dot-mauthor-dev.ew.r.appspot.com/present/5663212299091969)

2024-02-06 12:29 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +        const rightSideIndex = previousLeftSideIndex + presenter.configuration.numberOfButtons - 4;
Tutaj raczej nie masz pełnego wyliczenia. Chyba powinieneś odejmować jeszcze presenter.configuration.numberOfStaticPages
Spójrz na rozwiązanie w https://github.com/icplayer/icplayer/pull/1086

2024-02-06 12:30 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            this.setLeftOffset(1);
Dlaczego 1 ?

2024-02-06 12:32 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            this.shiftCount = Math.floor((presenter.sections.getActualPageIndex() + 1) / (presenter.configuration.numberOfButtons - 4));
Brak uwzględnienia stron stałych

2024-02-06 12:47 UTC, msawoniuk requested changes
Znaleziono błędy:
**Błąd 1**
1. Wejdź na lekcję: https://test-9054-dot-mauthor-dev.ew.r.appspot.com/present/4538519814930433
2. W pierwszym ANB kliknij na 12.
3. Kliknij dowolny stały guzik dla strony z mniejszym indeksem (np. 1, 2, 4 (stałe guziki po lewej stronie) lub 3 (stały guzik po prawej stronie)).
4. Wyskoczy błąd w setState

**Błąd 2**
1. Wejdź na lekcję: https://test-9054-dot-mauthor-dev.ew.r.appspot.com/present/4538519814930433
2. W pierwszym ANB kliknij na trzy kropki.
3. W pierwszym ANB kliknij na 10.
4. ANB się nie zaktualizował aby pokazać 9.

Oraz kilka uwag.

2024-02-06 12:47 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +        this.leftSideIndex += shift;
Nie rozumiem tego fragmentu. 
Jeżeli shift != 0:
* to dodaj shift do this.leftSideIndex
* jednocześnie nie uwzględniając shift w oblieczniu this.shiftCount

2024-02-06 12:47 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            this.shiftCount = Math.floor((presenter.sections.getActualPageIndex() + 1) / (presenter.configuration.numberOfButtons - 4));
Brak uwzględnienia stron stałych

2024-02-06 12:47 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +        const rightSideIndex = previousLeftSideIndex + presenter.configuration.numberOfButtons - 4;
Tutaj raczej nie masz pełnego wyliczenia. Chyba powinieneś odejmować jeszcze presenter.configuration.numberOfStaticPages
Spójrz na rozwiązanie w https://github.com/icplayer/icplayer/pull/1086

2024-02-06 12:47 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            this.setLeftOffset(1);
Proszę unikać magic numbers. Obecnie leftOffset może przyjmować wartości 0 lub 1. 
Dlatego proponuję stałego dictionary z stałymi np.
```
const OFFSET {
  NO_OFFSET: 0,
  STANDARD_OFFSET: 1
}
```
Ułatwi to czytanie kodu, bo później można przyrównywać leftOffset z jedną z stałych.

2024-02-06 12:47 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            this.shiftCount = Math.floor((this.leftSideIndex + 1) / (presenter.configuration.numberOfButtons - 4));
jw. z presenter.configuration.numberOfStaticPages

2024-02-09 08:43 UTC, msawoniuk requested changes
Powody declined:
1. Psują się testy setState i getState
2. Obawa o działanie po przyjęciu starego stanu. Wystarczy mi potwierdzenie, że takowe manualne testy ze starym stanem zostały wykonane.

Opcjonalnie:
1. Naprawienie problemu z magic numbers. Wydłuża to czytanie. Ze względu, że ten addon ma całkiem sporo takich magic numbers to pozostawiam to jako opcję

2024-02-09 08:43 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +            if (previousLeftSideIndex > 3) {
Magic number 3

2024-02-09 08:43 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +        const previousLeftSideValue = parsedState.leftSideValue;
Jak czytam kod to nie powinno nic wybuchnąć w przypadku podania starego stanu, gdzie tych wartości nie ma.
(undefined < 0) == false
oraz gdy previousLeftSideValue == undefined to także nie znajdzie tej strony.

Proponuję jednak, aby w nowych metodach była lepsza obsługa na przypadek undefined niż warunki if z wartością undefined. Ewentualnie nadanie nowej wartości, gdyby previousLeftSideIndex i previousLeftSideValue były puste. 

Czy były wykonywane testy, przynajmniej manualne z starym stanem ?

2024-02-12 08:38 UTC, maciej-zawlocki-solwit approved these changes

2024-02-15 07:39 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2024-02-16 08:31 UTC, maciej-zawlocki-solwit approved these changes

2024-02-21 08:14 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2024-02-22 07:25 UTC, merged