Added sa and gsa to points to plot, re #9058
icplayer/icplayer pull request #1102
Opened 2024-02-07 12:53 UTC by maciej-zawlocki-solwit

ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=9058
wersja testowa: https://test-9058-dot-mauthor-dev.ew.r.appspot.com/

2024-02-07 14:38 UTC, msawoniuk requested changes
"Moduł Points to Plot używany jest gdy uczeń ma możliwość zaznaczenia kilku poprawnych punktów w zakresie danej funkcji matematycznej w module Plot, co oznacza, że w zadaniu nie ma jednego, stałego zestawu poprawnych punktów do zaznaczenia."
To założenie moim zadaniem nie jest spełnione. "strict points" wymusza jakie punkty muszą być zaznaczone i tylko te punkty (jeżeli się nie mylę, to odpowiada za to presenter.getPointOnPlots). Oznacza to, że SA i GSA nie będzie działać z funkcjonalnością, gdzie "strict points" pozostawia się puste, podaje się liczbę punktów aby kod decydował, czy zaznaczony punkt należy do wykresu (patrz: https://www.mauthor.com/embed/4505122450178048#7)
Moim zdaniem powinny to być osobne property o czym także pisali w opisie zadania.

Wydaje mi się, że powinniśmy to traktować jako błąd. Można dopytać o to osobę z LEA. Wydaje mi się, że SA i GSA nie powinny sprawiać znikanie wykresu.
1. Wejdź na lekcję https://test-9058-dot-mauthor-dev.ew.r.appspot.com/present/6390975180046337
2. Włącz SA - Wykres znika

2024-02-07 14:38 UTC, msawoniuk commented on addons/Points_To_Plot/src/presenter.js
> +        sourceModule.saveAndClearPlot();
Myślę, że czyszczenie całego wykresu nie jest oczekiwanym zachowaniem. Poza punktami znikają także wykresy.

2024-02-07 14:38 UTC, msawoniuk commented on addons/Points_To_Plot/src/presenter.js
> +        sourceModule.saveAndClearPlot();
j.w.

2024-02-13 07:28 UTC, msawoniuk requested changes
Błędy na wersji testowej:
1. Brak wyłączenia SA dla Check Answers

Opcjonalnie:
1. Poprawić nazwę zmiennej
2. Napisać testy pod upgrade model

2024-02-13 07:28 UTC, msawoniuk commented on addons/Points_To_Plot/src/presenter.js
> +        var rawShawAnswers = model['Show answers'].trim();
Mała literówka. Do poprawy w przypadku, gdyby zadanie wróciło.
rawShawAnswers -> rawShowAnswers

2024-02-13 07:28 UTC, msawoniuk commented on addons/Points_To_Plot/src/presenter.js
>      presenter.setShowErrorsMode = function() {
Check Answers nie wyłącza SA. 
Użyj "isShowAnswersActive && presenter.hideAnswers()" lub "presenter.hideAnswers()"

Objawia się to dwoma błędami:
1. Kliknięcie SA a potem Check answers wyświetla punkty z SA.
2. Po wykonaniu błędu numer 1 wyłączenie SA powoduje zniknięcie odpowiedzi użytkownika do momentu ponownego włączenia Check answers. Możliwe, że ten błąd jest bardziej skomplikowany.

2024-02-14 09:12 UTC, maciej-zawlocki-solwit commented
Poprawiłem błąd z check answers i literówkę, testów nie dodawałem ponieważ ticket i tak już się przedłuża.

2024-02-14 09:33 UTC, msawoniuk requested changes
Niestety znalazłem kolejny błąd.
Wydaje mi się, że to wcześniej sprawdzałem i było OK. Jeżeli nie to przepraszam za przeoczenie.

Błąd:
1. Wejdź na https://test-9058-dot-mauthor-dev.ew.r.appspot.com/present/6390975180046337
2. Zaznacz kilka punktów
3. Włącz SA (nie ma tego problemu dla GSA)
4. Przejdź na inną stronę
5. Wróć na poprzednią stronę
6. Odpowiedzi użytkownika nie widać (jednak istnieją). Włączenie CheckAnswers je wyświetla. Dalej można zaznaczać punkty i CheckAnswers wyświetli wszystkie (łączenie z tymi niewidocznymi).

2024-02-14 19:06 UTC, wkarasSolwit submitted a review, later dismissed
OK
dwie uwagi, ale nie blokujące

2024-02-14 19:06 UTC, wkarasSolwit commented on addons/Points_To_Plot/src/presenter.js
> +        isShowAnswersActive = false;
imo ustawienie flagi na false powinno być za metodą ptpHideAnswers(), zwłaszcza, że jeżeli jakiś trafem nie będzie sourceModule to metoda ptpHideAnswers() się nie wykona

2024-02-14 19:06 UTC, wkarasSolwit commented on addons/Points_To_Plot/src/presenter.js
> +        isShowAnswersActive = true;
podobna uwaga jak wyżej

2024-02-16 11:42 UTC, merged