Add reset, redo and undo buttons to Geometric Construct
icplayer/icplayer pull request #1143
Opened 2024-05-20 08:45 UTC by maciej-zawlocki-solwit

ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/9245-nale%C5%BCy-doda%C4%87-mo%C5%BCliwo%C5%9B%C4%87-cofni%C4%99cia-ponownego-wstawienia-zmian/details
Wersja testowa: https://test-9245-dot-mauthor-dev.ew.r.appspot.com/present/6584946405670913

2024-05-22 09:08 UTC, wkarasSolwit reviewed
brak zmian w changelog
poprawka dok

2024-06-04 06:16 UTC, msawoniuk reviewed
Odnośnie wypowiedzi punkt Ad.3 https://learneticsa.assembla.com/spaces/dbI9RCSvmr4iQBeJe4gwI3/tickets/9245/details?comment=1712611868 to mam wątpliwość, że takie zachowanie mimo tego komentarza jest oczekiwane. Jeżeli addon nie będzie defualtowo widoczny to reset jako guzik dostarczany przez addon spowoduje reset widoczności - czyli wyłączy jego widoczność. Jest to nieintuicyjne - z tego powodu nie daję ani approve ani RC - zostawiam tu komentarz i pytam w tasku

2024-06-04 08:16 UTC, msawoniuk requested changes
Zmieniam na Request changes po otrzymaniu odpowiedzi od Agnieszki

2024-06-12 07:06 UTC, msawoniuk approved these changes

2024-06-12 07:06 UTC, msawoniuk commented on addons/GeometricConstruct/src/presenter.js
> +            presenter.previousStates.splice(presenter.prevStateIndex + 1 - presenter.previousStates.length);
Aby nie zniknęło zostawiam odpowiedź:
"jeżeli cofniemy się o X stanów, a potem utworzony zostanie nowy stan, to te X trzeba porzucić" aby nie móc do nich wrócić przez nextState

2024-06-20 08:18 UTC, merged