Added arc with center point to geometric constructs, re #9248
icplayer/icplayer pull request #1156
Opened 2024-06-25 07:32 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/9248-dodanie-elementu-%C5%82uk-o-danym-%C5%9Brodku/details
Wersja testowa: https://test-9248-dot-mauthor-dev.ew.r.appspot.com/present/4922738495979521

2024-06-25 10:37 UTC, msawoniuk requested changes
Odrzucam z powodu serii błędów. 
Niektórych błędów nie mogłem zreprodukować, ale jest duża szansa, że one były spowodowane tym samym problemem

2024-06-25 10:37 UTC, msawoniuk commented on addons/GeometricConstruct/src/presenter.js
> +            var point = presenter.getClickedOrCreatePoint(event);
Edit 3. Problem się pogłębia.
1. Stwórz jeden arc with center point
2. Zacznij tworzyć drugi arc with center point ale jako jeden z punktów użyj punktu z kroku 1 (np. użyj punkt początkowy z kroku 1), ale nie kończ tworzenia tej figury!
3. Przejdź na inną stronę.
4. Stwórz punkt. Będzie miał label (duplikacja labelek) identyczny do punktu jaki został wybrany w kroku 2.

2024-06-25 10:37 UTC, msawoniuk commented on addons/GeometricConstruct/src/presenter.js
Edit.
W trakcie testów pojawiły się dwa błędy dla których nie mogłem odtworzyć kroków.
1. Raz był problem z getState
2. Raz był problem że labelki były tworzone z błędną kolejnością. Było stworzone B potem E i F. Z jakiegoś powodu pominął A i C.

2024-06-26 07:38 UTC, maciej-zawlocki-solwit commented on addons/GeometricConstruct/src/presenter.js
> +                    if (this.arcEndPoint != null) {
Po zmianach w insertArcEndPoint jest teraz możliwe, żeby this.arcEndPoint był null'em.

2024-06-26 07:42 UTC, maciej-zawlocki-solwit commented on addons/GeometricConstruct/src/presenter.js
> +            var point = presenter.getClickedOrCreatePoint(event);
1) Zablokowałem możliwość ustawienia punktu środkowego i startowego łuku jako punkt końcowy łuku.
2) Kod odpowiedzialny za usunięcie z listy w zapisywanym stanie labelek należących do nieprawidłowych (i w związku z tym niezapisywanych) figur (w tym wypadku figury, która nie została jeszcze w pełni skonfigurowana) nie uwzględniał możliwości, że te labelki mogą jeszcze należeć do innych figur. Błąd został poprawiony.

2024-06-26 07:43 UTC, maciej-zawlocki-solwit commented on addons/GeometricConstruct/src/presenter.js
1) Wprowadziłem zmianę, żeby wszystkie elementy figury były usuwane, jeśli jej tworzenie będzie przerwane poprzez zmianę opcji w toolbar'ze.
2) Nie byłem w stanie odtworzyć błędów. Prawdopodobnie były one powiązane z nieprawidłowościami w zapisywanym stanie, więc być może pozostałe poprawki w nich pomogą.

2024-06-26 11:38 UTC, wkarasSolwit approved these changes
ok

2024-06-26 12:21 UTC, merged