feat(addons): add calculating total score from all pages, re #9083
icplayer/icplayer pull request #1168
Opened 2024-07-24 08:13 UTC by wkarasSolwit

[Ticket](https://app.assembla.com/spaces/lorepo/tickets/9083-hlr---dodanie-property-exclude-unvisited-pages-in-the-total/details)
[Wersja testowa](https://test-9083-dot-mauthor-dev.ew.r.appspot.com)
[Lekcja](https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/6608587742773249)

2024-07-24 13:50 UTC, msawoniuk requested changes

2024-07-24 13:50 UTC, msawoniuk commented on addons/Hierarchical_Lesson_Report/src/presenter.js
> +    presenter.setPagesVisited = function () {
Addon ustawia, że wszystkie strony zostały odwiedzone. Zmiana ta wpłynie na inne addony (najprawdopodobniej tylko te od punktacji) jednak też będzie wpływać na punktację w lekcji. mC korzysta z PlayerUtils w celu wyliczenia punktów. W PlayerUtils w getPresentationScoreBase dla stron raportowalnych dla pewnej ścieżki wpływa to na zmianę punktacji w lekcji. 

Zgodnie z opisem w tickecie addon ma mieć zmienione obecne zachowanie dlatego mam duże obawy, że wystąpią przez to problemy. W opisie zadania jest napisane o zmianie punktacji "jakby" wszystkie strony były odwiedzone. Natomiast obecne rozwiązanie sprawi, że wszystkie strony "zostaną" odwiedzone. 

Dodatkową obawą jest dla mnie działanie Adaptive Learning - Działa to tak, że daje się warunki aby wybrać strony lekcji na które można wejść. Możliwe, że istnieje content, który sprawdza czy jakaś strona została odwiedzona lub jest przyznawany punkt tylko za odwiedzenie strony (bo można wejść tylko na jedną z dwóch stron).

Prywatnie pisaliśmy o tymczasowej zmianie stanu odwiedzenia tych stron. Niestety mam wrażenie, że takie rozwiązanie także naraża na błędy. W mC można ustawić, aby co kilka sekund był zapisywany wynik (automatyczny zapis). Jeżeli wykonałby się w takcie tej operacji to powstaną nieprawidłowości.
Widzę, że w lekcji korzysta się z presenter.isPageVisited. W pierwszej kolejności proszę sprawdź czy nie wystarczy tam zwracać true jeżeli nowe property jest odznaczone.

2024-07-26 08:22 UTC, msawoniuk requested changes
Nie działa poprawnie przywracanie stanu visitedPages. Proszę, skup się wpierw na modyfikacji związanej z presenter.isPageVisited i miejsc gdzie jest to wykorzystane. Nawet, jeżeli obecne rozwiązanie z przywracaniem będzie naprawione to dalej stwarza podatność o czym napisałem wcześniej.
1. Na wskazanej lekcji testowej wszedłem na pierwszą stronę i wykonałem komendę, Potem na piątą z HLR i wykonałem komendę. W efekcie zmiany została wyczyszczona informacja o odwiedzeniu pierwszej strony.
![image](https://github.com/user-attachments/assets/31a09c38-0aeb-4762-9f6b-ffe36f384b92)
2. Nie działa cel czyszczenia stanu - czyli oczekiwanego brak wpływu na PlayerUtils. Wejdź na moją lekcję: https://test-9083-dot-mauthor-dev.ew.r.appspot.com/embed/5922458764836865. Strona 3 ma maxScore równy 0 i jest raportowalna. Czyli po odwiedzeniu otrzyma 1 score. Wejdź na lekcję i przejdź od razu na 6 stronę z addonem HLR. Addon poprawnie pokazuje. PlayerUtils pokazuje jak HLR czego robić nie powinien. 
![image](https://github.com/user-attachments/assets/900f3c3e-7bf2-4e51-bd68-338d79823846)

Dalsze testy, gdzie coś mogło się popsuć przerwałem.

2024-07-26 08:23 UTC, msawoniuk commented on addons/Hierarchical_Lesson_Report/src/presenter.js
Dokumentacja nie została poprawiona o nowe property

2024-07-29 08:05 UTC, msawoniuk requested changes
Rozwiązanie nie działa poprawnie.
1. Jak w komentarzu poniżej - "presenter.isPageVisited" masz błędnie napisany warunek przez co przy zaznaczonym tym property addon nie działa jak wcześniej. 
2. Total nieprawidłowo się zachowuje. Znalazłem dwie błędne sytuację: 
2.1. Czym więcej odwiedzi się stron to total jest mniejszy. Zdjęcie po odwiedzeniu każdej ze stron.
![image](https://github.com/user-attachments/assets/8db70bce-6c42-46da-87a9-5e34fc5a0f45)
2.2. Jeżeli odwiedzi się tylko raportowalną stronę i przejdzie się na HLR - strona 6 to total pokaże 100%. Jeżeli odwiedzi się kolejną to 50% itd. Jest to zachowanie obserwowane także na produkcji - czyli twoje zmiany nie wpłynęły na to jak powinny

2024-07-30 07:30 UTC, msawoniuk requested changes
Kod wygląda na OK, jednak jest jeszcze kilka problemów.
I. Po zaznaczeniu nowego property nie są uwzględniane nieodwiedzone strony. Czyli ma działać po staremu. Więc jeżeli każdą stronę się odwiedzi to addon z zaznaczonym property i nienaznaczonym powinny pokazywać ten sam wynik w total. Obecnie tak się nie dzieje. 
1. Wejdź na https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/5932272765108225#7
2. Uzupełnij poprawnie drugą stronę lekcji.
3. Odwiedź każdą stronę.
4. Total (procentowe) będzie różne dla każdego z addonów. Dla jednego 25%, dla drugiego 50%
II. Myślę, że oczekiwany efekt nie jest uzyskany. Temat do dyskusji
1. Wejdź na https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/5932272765108225#1
2. Odwiedź czwartą stronę i uzupełnij poprawnie część strony.
3. Idź na stronę 6 i 7.
4. Idź na stronę 3
5. Wróć na stronę 6 i 7. Odwiedzenie strony raportowalnej bez activity pozytywnie wpływa na total na ostatniej stronie w przypadku strony 7. Dla strony 6 nie robi to znaczenia. Jeżeli otrzymuje się 100% za odwiedzoną stronę (w tym przypadku) to myślę, że powinno mieć to wpływ na total.

Proszę o lekcję testową która ma te dwie strony (3 i 7) z mojej lekcji, w celu usprawnienia przyszłych testów akceptacyjnych

2024-08-07 08:48 UTC, msawoniuk requested changes
Przepraszam, że tego wcześniej nie sprawdziłem. 
Drukowalne wersje kodu wybuchają - w konsoli deweloperskiej więcej info.
Ogólnie to problem polega na tym, że są dwie configuration.
presenter.configuration i presenter.printableConfiguration
Dlatego w miejscach, gdzie drukowalna i normalna wersja korzystają z tego samego kodu będziesz musiał wywoływać getConfiguration().excludeUnvisitedPages 

Zobacz też czy nie wystąpi błędne liczenie score w drukowalnej wersji. Patrząc na getLessonScore to mam takie przeczucie.

Błędnie jest liczone przy zaznaczonym "Use weighted arithmetic mean" - jakby twoje zmiany się "wyłączały" po zaznaczeniu tego property

2024-08-07 08:48 UTC, msawoniuk commented on addons/Hierarchical_Lesson_Report/src/presenter.js
> +        } else if (presenter.isPageVisited(pageId) && presenter.configuration.excludeUnvisitedPages) {
Tu raczej jest błąd - do analizy.
Po zaznaczeniu property isWeightedArithmeticMean addon zachowuje się jakby Twoje zmiany przestały działać.  Tzn. TotalScore jest identyczny niezależnie czy zostanie zaznaczone nowe property. 

Reprodukcja:
1. Wejdź na https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/5932272765108225
2. Uzupełnij stronę 2, 3 i 4.
3. Przejdź na stronę 11 i 12. Na obu będzie ten sam wynik mimo, że jeden ma (12 strona) zaznaczone nowe property.

2024-08-09 07:32 UTC, msawoniuk requested changes
Przerywam CR. 
Drukowalna wersja dalej wybucha.
Problem z "Use weighted arithmetic mean" dalej występuje.
Prośba o testy z użyciem wersji testowej: https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/5932272765108225

2024-08-13 06:17 UTC, maciej-zawlocki-solwit approved these changes

2024-08-20 15:50 UTC, msawoniuk requested changes
Powody odrzucenia:
1. Drukowalne wersje nie działają. Nie wnikałem w szczegóły jednak na wersji testowej https://test-9083-dot-mauthor-dev.ew.r.appspot.com/present/5932272765108225 po odwiedzeniu strony z addonem HLR np. 9 i użyciu funkcjonalności "Print preview" -> User answers jest błąd w konsoli deweloperskiej.
![image](https://github.com/user-attachments/assets/ca2d6176-f275-4720-b3ba-7dbb33805be4)
Na mauthor-dev nie ma tego problemu.
2.  Powód identyczny jak w https://github.com/icplayer/icplayer/pull/1168#pullrequestreview-2223021907 oraz https://github.com/icplayer/icplayer/pull/1168#pullrequestreview-2229539259 . Brak zmian w zachowaniu działania addonu przy zaznaczonym "Use weighted arithmetic mean". Treść zadania wspomina o tym polu, więc do zakończania zmiany zadanie nie spełnia wymogów. Jeżeli miałoby to być wykonywane w osobnym zadaniu to zaproponuj to w tickecie. Proszę się odnieść jakie są plany wobec tego property.

2024-08-20 15:50 UTC, msawoniuk commented on addons/Hierarchical_Lesson_Report/src/presenter.js
> +        if (score.maxScore === 0 && getConfiguration().includeUnvisitedPages && pageId && presentationController) {
Możliwe, że po naprawieniu blędu jak z podsumowania będzie trzeba stworzyć reprezentację tego dla drukowalnej wersji. presentationController jest dostępny tylko w niedrukowalnej wersji.

2024-09-12 07:57 UTC, maciej-zawlocki-solwit approved these changes

2024-09-12 10:20 UTC, merged