Added show/hideAngleLabels to the Geometric Construct addon, re #9257
icplayer/icplayer pull request #1174
Opened 2024-07-31 12:23 UTC by maciej-zawlocki-solwit

ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/9257-guzik-show-hide-angle-measures/details
Wersja testowa: https://test-9257-dot-mauthor-dev.ew.r.appspot.com/present/5807461426528257

2024-08-01 13:46 UTC, msawoniuk requested changes
Reset nie resetuje addonu do początkowego stanu.
Bym powiedział, że zrób tak samo jak z labelkami ale jest błąd na produkcji.
W linijce 2720 nowego kodu powinno być:
`presenter.setLabelsVisibility(presenter.configuration.labelsDefaultVisibility);`
Obecne `presenter.labelsDefaultVisibility` nigdy nie jest ustawiane co świadczy, że był zamysł aby to resetować. Zaś do `presenter.configuration.labelsDefaultVisibility` jest ustawiana wartość.
Proszę popraw informację w changelog i dokumentacji.
Fajnie by było aby były testy na aktualizację modelu - nieblokujące.

2024-08-01 13:46 UTC, msawoniuk commented on addons/GeometricConstruct/documentation.md
> +        <td>Displays the labels of angles in the workspace if they were hidden</td>
brakuje kropki na końcu

2024-08-01 13:46 UTC, msawoniuk commented on changelog.txt
> +2924-07-31 Added show/hideAngleLabels to the Geometric Construct addon
Takiego roku się nie spodziewałem :P

2024-08-02 08:05 UTC, wkarasSolwit approved these changes
OK

2024-08-09 08:04 UTC, wkarasSolwit requested changes
Na wersji testowej występuje błąd:
po przejściu na inną stronę i powrocie, pojawia się symbol kąta, pomimo, że opuszczając stronę wszystkie opisy (labels) były wyłączone.
Kroki do odtworzenia:
- dodać kąt
- wyłączyć opisy
- przejść na inną stronę
- wrócić do pierwotnej
- na pierwotnej wyświetla się symbol kąta

2024-08-09 08:56 UTC, wkarasSolwit approved these changes
OK

2024-08-19 08:18 UTC, msawoniuk submitted a review, later dismissed

2024-08-21 13:04 UTC, merged