feat(addons): add pages list dropdown section in ANB, re #8
icplayer/icplayer pull request #1205
Opened 2024-09-29 19:28 UTC by wkarasSolwit

[ticket](https://learnetic.youtrack.cloud/issue/PLA-8/ANB-dodanie-funkcji-rozwijalnej-listy-stron)
[wersja testowa](https://test-8-dot-mauthor-dev.ew.r.appspot.com/)
[lekcja](https://test-8-dot-mauthor-dev.ew.r.appspot.com/present/5782340540301313)

2024-10-11 07:00 UTC, maciej-zawlocki-solwit approved these changes

2024-10-16 07:11 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2024-10-21 09:50 UTC, msawoniuk requested changes
Powody odrzucenia:
1. Nawigacja klawiaturowa nie działa w pełni poprawnie.
ANB umożliwia przechodzenie między stronami - wiec po przejściu na inną stronę z użyciem ANB i nawigacji TTS powinno móc się nawigować jak wcześniej. Obecnie po przejściu na inną stronę można nacisnąć lewą strzałkę lub prawą, aby nawigować tylko po strzałkach - omijane są sekcje.
2. Wpływ w stylach CSS na istniejący content
3. Jeżeli ANB jest stosunkowo małe: https://test-pla-8-dot-mauthor-dev.ew.r.appspot.com/present/5984454201835521 to nie widać guzika do przejścia na "Chapter with one page"

Proszę o stworzenie paczki icplayer.zip oraz wystawienie Twej lekcji na mC, aby móc przetestować na np. mLibro mobile. 

ad.3 dla widoku mobilnego wprowadzono scrollowanie zawartości - dlatego nie zmieniałem dotychczasowych ustawień dla przycisków sekcji

AD.3. Masz rację. Jeszcze raz spojrzałem na lekcję i przez to, że ANB w mojej lekcji nie był na tyle wysoki to nie była widoczna sekcja dla tamtego guzika. Edytowałem wysokość i jest ok https://test-pla-8-dot-mauthor-dev.ew.r.appspot.com/present/5984454201835521

2024-10-21 09:50 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/style.css
> +    display: flex;
Obawiam się, że może to popsuć istniejący content. Tj. modyfikujesz style, dla elementów które już istnieją. Najlepiej byłoby dodać dodatkową klasę na to.

2024-10-21 09:50 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/style.css
> +    position: relative;
jw.

2024-10-22 19:08 UTC, wkarasSolwit commented on addons/Assessments_Navigation_Bar/documentation.md
> -    <td>Use dynamic pagination</td>
poprawione

2024-10-22 19:13 UTC, wkarasSolwit commented on addons/Assessments_Navigation_Bar/src/style.css
> +    position: relative;
poprawione

2024-10-23 08:24 UTC, msawoniuk requested changes
Proszę o skasowanie log'a oraz wystawienie paczki, aby móc sprawdzić rozwiązanie pod mLibro mobile

2024-10-23 08:24 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/documentation.md
> -    <td>Use dynamic pagination</td>
ok

2024-10-23 08:24 UTC, msawoniuk commented on addons/Assessments_Navigation_Bar/src/presenter.js
> +        console.log('run 21')
tego tu nie powinno być

2024-10-23 09:17 UTC, msawoniuk submitted a review, later dismissed
OK.
Ostatecznie nie udało mi się przetestować tego na mLibro. Chyba jest to błąd związany z nowym importerem/eksporterem.

2024-10-25 10:13 UTC, merged