fix(addons): not rendering mathjax after changing layout or metadata, re #pla-31
icplayer/icplayer pull request #1219
Opened 2024-10-25 14:40 UTC by wkarasSolwit

[ticket](https://learnetic.youtrack.cloud/issue/PLA-31/BUG-Po-przelaczeniu-kontekstu-albo-zmianie-layoutu-znika-MathJax)
[Wersja testowa](https://test-pla-31-dot-mauthor-dev.ew.r.appspot.com)
[Lekcja](https://test-pla-31-dot-mauthor-dev.ew.r.appspot.com/present/6391842302066689)

2024-10-28 10:35 UTC, maciej-zawlocki-solwit commented
Rozwiąż proszę ten konflikt w PlayerEntryPoint (co jest raczej trywialne), poza tym ok.

2024-10-29 06:27 UTC, maciej-zawlocki-solwit approved these changes

2024-10-30 10:26 UTC, msawoniuk requested changes
Proszę o skasowanie zbędnych importów i odniesienie się do pytania

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerApp.java
> +import com.lorepo.icplayer.client.module.limitedreset.LimitedResetView;
Zbędny import

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerApp.java
> +import com.lorepo.icplayer.client.module.api.event.ValueChangedEvent;
Zbędny import

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerApp.java
> +import com.lorepo.icplayer.client.PlayerApp.PlayerConfigOverlay;
Zbędny import

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerApp.java
> +import com.lorepo.icplayer.client.PlayerApp.PlayerEventsConfigOverlay;
Zbędny import

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerApp.java
> +            x.@com.lorepo.icplayer.client.PlayerApp::updateMathJax()();
złe wcięcie

2024-10-30 10:26 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerEntryPoint.java
> +				entryPoint.@com.lorepo.icplayer.client.PlayerEntryPoint::updateMathJax()();
Czy ta zmiana jest konieczna ?

2024-10-30 12:50 UTC, wkarasSolwit commented on src/main/java/com/lorepo/icplayer/client/PlayerEntryPoint.java
> +				entryPoint.@com.lorepo.icplayer.client.PlayerEntryPoint::updateMathJax()();
tak, jest potrzebna

2024-10-30 15:46 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/PlayerEntryPoint.java
> +				entryPoint.@com.lorepo.icplayer.client.PlayerEntryPoint::updateMathJax()();
ok

2024-10-30 15:46 UTC, msawoniuk submitted a review, later dismissed

2024-11-04 08:33 UTC, msawoniuk approved these changes

2024-11-04 11:31 UTC, merged