fix(addons): score counting in draggable gaps, re#pla-101
icplayer/icplayer pull request #1243
Opened 2024-12-04 16:09 UTC by wkarasSolwit

[ticket](https://learnetic.youtrack.cloud/issue/PLA-101/Blad-w-obsludze-formatowania-html-w-gapach-dragowalnych-Text)

2024-12-05 13:19 UTC, msawoniuk requested changes
Rozwiązanie nie jest wystarczające.
Maciej ostatnio pracował nad podobnym zadaniem PLA-85. Może to pomoże.

2024-12-05 13:19 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextPresenter.java
> +		return value.contains("<b>") || value.contains("<i>") || value.contains("<s>");
Ta lista tagów jest niewystarczająca. 
Pierwotnie chciałem napisać o dodaniu pełnej listy (jeżeli taka istnieje), jednak chyba wystarczy ta wspierana przez TextEdytor. Upewniłem się do tego przypadku z tagiem <u>. Jest ich więcej
![image](https://github.com/user-attachments/assets/df72a2b2-5ef9-4745-b985-fdd895624777)

2024-12-05 13:19 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextPresenter.java
> +		String pattern = "[a-zA-Z0-9]+<[a-zA-Z0-9\\s]+.*";
Rozumiem sprawdzenie czy to matematyczna formuła ale nie rozumiem zastosowania tego konkretnego regexa.
Widzę, że regex znajdzie `1<1` lecz `1 < 1` już nie. Jeżeli ten regex nie ma za zadanie złapać dowolnej matematycznej formuły a jakiś inny cel to proszę o bardziej dopasowaną nazwę.
![image](https://github.com/user-attachments/assets/41b6d9e3-95f1-4759-854d-9b24ece611f2)
Na powyższym zdjęciu podawane jest `x<3` i błąd dalej się reprodukuje.

2024-12-06 09:57 UTC, maciej-zawlocki-solwit approved these changes

2024-12-12 08:34 UTC, maciej-zawlocki-solwit approved these changes

2024-12-13 11:29 UTC, msawoniuk approved these changes

2024-12-13 11:30 UTC, merged