feat(addons): include transparent areas in checking answer, re#108
icplayer/icplayer pull request #1245
Opened 2024-12-09 10:49 UTC by wkarasSolwit

[ticket](https://learnetic.youtrack.cloud/issue/PLA-108/Coloring-oznaczanie-poprawnosci-pola-transparent)

2024-12-09 15:35 UTC, msawoniuk requested changes
Poza zaznaczonymi obszarami:
1. Brak zmian w dokumentacji - wstrzymujące
2. Mimo, że w tickecie nie ma napisane o tym bezpośrednio to zakładam, że TTS też powinno współpracować z nową funkcjonalnością Sprawdź tą lekcję https://test-pla-108-dot-mauthor-dev.ew.r.appspot.com/present/4806853223514113 . - wstrzymujące
3. Jedna rzecz wydawała mi się dziwna, jednak twa implementacja jest zgodna z tym co w opisie. Dlatego dopytuję LEA w celu upewnienia się, że nie zapomnieli o jednym scenariuszu - zależy od odpowiedzi LEA czy wstrzymujące
4. Szkoda, że nie napisałeś bardziej rozpisanych testów - niewstrzymujące z uwagi na ilość już poświęconego czasu

2024-12-10 16:18 UTC, wkarasSolwit commented
> Poza zaznaczonymi obszarami:
> 
> 1. Brak zmian w dokumentacji - wstrzymujące
> 2. Mimo, że w tickecie nie ma napisane o tym bezpośrednio to zakładam, że TTS też powinno współpracować z nową funkcjonalnością Sprawdź tą lekcję https://test-pla-108-dot-mauthor-dev.ew.r.appspot.com/present/4806853223514113 . - wstrzymujące
> 3. Jedna rzecz wydawała mi się dziwna, jednak twa implementacja jest zgodna z tym co w opisie. Dlatego dopytuję LEA w celu upewnienia się, że nie zapomnieli o jednym scenariuszu - zależy od odpowiedzi LEA czy wstrzymujące
> 4. Szkoda, że nie napisałeś bardziej rozpisanych testów - niewstrzymujące z uwagi na ilość już poświęconego czasu

2024-12-11 09:44 UTC, msawoniuk requested changes
Prawie wszystko co zaznaczyłem zostało poprawione.
Pozostają dwie rzeczy, które wcześniej zaznaczyłem:
1. Niepotrzebnie skasowany test
2. Brak wsparcia TTS pod nową zmianę. Proszę użyj wcześniejszego mojego linku. W lekcji, którą podałeś nie będzie możliwe przetestowanie tego! Powinna to być łatwa poprawka. To co zauważyłem że nie działa. Po wejściu na lekcję https://test-pla-108-dot-mauthor-dev.ew.r.appspot.com/present/4806853223514113 i aktywacji TTS to po użyciu CheckAnswers pojawiają się te ikony. Twoja zmiana powoduje że pojawia się ikona dla pola oznaczonego dla transparent. To co nie działa to, nie czyta TTS'a "Correct" dla tej nowej ikonki. 
![image](https://github.com/user-attachments/assets/48e7a91f-5237-46d1-bbc7-8cb84f60d30b)

2024-12-13 09:37 UTC, maciej-zawlocki-solwit approved these changes

2024-12-13 10:58 UTC, maciej-zawlocki-solwit approved these changes

2024-12-18 07:54 UTC, maciej-zawlocki-solwit approved these changes

2024-12-18 14:33 UTC, msawoniuk submitted a review, later dismissed

2024-12-20 11:21 UTC, merged