Fixed issues with m3u8 in video on ios devices, re #pla-110
icplayer/icplayer pull request #1248
Opened 2024-12-18 13:46 UTC by maciej-zawlocki-solwit

Ticket: https://learnetic.youtrack.cloud/issue/PLA-110/Video-HLS-nie-dziala-na-urzadzeniach-ios
Wersja testowa: https://test-pla-110-dot-mauthor-dev.ew.r.appspot.com/present/5005512640823297

Uwagi - brak testów wynika z przekroczenia estymaty.

2024-12-19 08:18 UTC, msawoniuk requested changes
Wstrzymuję z powodu przestania działania addonu po powrocie na stronę z addonem gdy jest użyty inny format nagrania niż ten nowy.

Nie wstrzymujące z powodu sytuacji:
1. progress bar jest nieprawidłowo przeskalowany - może to być problem niezwiązany z dodaniem nowego formatu audio. Dodaję, gdyż w https://github.com/icplayer/icplayer/pull/1244 zostało o tym napisane
2. Brak poprawy isOnlineResourceOnly sprawdzającej czy zasób jest tylko dostępny online. Ważne pod działanie na mLibro offline - z uwagi na brak dostosowania mLibro pod nowy importer nie mogłem przetestować skutków
3. Brak wsparcia na mauthor-dev.

2024-12-19 12:48 UTC, msawoniuk reviewed
Poza zaznaczonymi sprawdziłem też testy, 
Na produkcji nie działają 2/77
Na Twej wersji 7/71 z czego te 5 wynikają z 
"Cannot read properties of null (reading 'find')"

2024-12-19 12:48 UTC, msawoniuk commented on addons/video/src/presenter.js
> +                $(presenter.videoObject).unbind("canplay");
Czy nie powinno tu być $(presenter.videoObject).unbind("loadedmetadata"); ?

2024-12-19 12:48 UTC, msawoniuk commented on addons/video/src/presenter.js
> +        $(presenter.videoObject).on(eventType, function onVideoCanPlay() {
Czy nie powinno być 
$(this).off(eventType);
zamiast 
$(this).off('canplay');
w 1578 linii ?

2024-12-19 12:54 UTC, msawoniuk approved these changes
Jest kilka uwag niewstrzymujących

2024-12-20 11:22 UTC, merged

2025-01-23 09:54 UTC, heejin-jeong commented
window.videojs This is always **undefined** and never makes the hls module **true**. I updated all the files but the problem persists. Can you check?