Fixed Test Puzzle error on firefox when entering a page in show errors mode (#7852)
icplayer/icplayer pull request #506
Opened 2021-03-05 14:46 UTC by msawoniuk

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/7852-puzzle---b%C5%82%C4%85d-na-firefox-przy-wej%C5%9Bciu-na-stron%C4%99-w-trybie-s/details
Wersja testowa: https://test-7852-dot-mauthor-dev.ew.r.appspot.com
Lekcja z wersją testową: https://test-7852-dot-mauthor-dev.ew.r.appspot.com/embed/6351719879409664#2

Jak przetestować:
1. Stworzyć drugą stronę
2. Stworzyć na drugiej stronie Puzzle oraz Limited Check wskazujący na puzzle
3. Włączyć Limited Check
4. Przełączyć na pierwszą stronę a następnie powrócić na drugą stronę
5. Wyłączyć Limited Check

2021-03-10 06:43 UTC, maciej-zawlocki-solwit requested changes
1) Co jeżeli InitPuzzle wykona się przed setPlayerController? 
2) Co jeżeli setShowErrors zostanie wykonane przed setPlayerController?
Jakkolwiek te problemy wydają się mało prawdopodobne, to mieliśmy już na tyle dużo problemów z "niespodziewaną" kolejnością żeby do tego podchodzić ostrożnie. Czy jest jakiś powód, dla którego wywołujesz InitPuzzleBoard w setPlayerController zamiast w run (tuż przed jImg wydaje się dobrym momentem)? Jeśli nie, prosiłbym żeby to przenieść.

2021-03-10 07:15 UTC, msawoniuk commented
> 1. Co jeżeli InitPuzzle wykona się przed setPlayerController?
> 2. Co jeżeli setShowErrors zostanie wykonane przed setPlayerController?
>    Jakkolwiek te problemy wydają się mało prawdopodobne, to mieliśmy już na tyle dużo problemów z "niespodziewaną" kolejnością żeby do tego podchodzić ostrożnie. Czy jest jakiś powód, dla którego wywołujesz InitPuzzleBoard w setPlayerController zamiast w run (tuż przed jImg wydaje się dobrym momentem)? Jeśli nie, prosiłbym żeby to przenieść.

InitPuzzleBoard jest wykonywane w run. W setPlayerController nic nie zmieniałem.

2021-03-10 07:32 UTC, maciej-zawlocki-solwit approved these changes

2021-03-15 08:03 UTC, tkrassowski approved these changes

2021-03-15 08:03 UTC, merged