Fix numeric gaps for ipad
icplayer/icplayer pull request #507
Opened 2021-03-09 12:20 UTC by rwojdak

2021-03-09 12:48 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2021-03-11 06:15 UTC, maciej-zawlocki-solwit approved these changes

2021-03-11 06:21 UTC, maciej-zawlocki-solwit requested changes
W chwili obecnej w ogóle nie da się wprowadzić tekstu innego niż numeryczny

2021-03-11 06:25 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2021-03-11 14:19 UTC, maciej-zawlocki-solwit commented
Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=7853

2021-03-12 10:25 UTC, tkrassowski commented on src/main/java/com/lorepo/icplayer/client/module/text/GapWidget.java
> +	private final String expNotationPattern = "-?\\d*([,.]\\d*)?(e[+\\-]?\\d*)?";
Można by dać przykład tego stringa, który się wpasowuje w ciag.

2021-03-12 10:25 UTC, tkrassowski commented on src/main/java/com/lorepo/icplayer/client/module/text/GapWidget.java
> +					if (gapInfo.isNumericOnly()) {
Standardowo, fajnie byłoby mieć test pod to, żeby lepiej wiedzieć co się wpasowuje lub nie.

2021-03-12 11:45 UTC, tkrassowski approved these changes

2021-03-12 12:51 UTC, merged