Fixed not being able to listen to audio items in multiplegap using keyboard navigation, #7923
icplayer/icplayer pull request #539
Opened 2021-04-08 06:02 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=7923
Wersja testowa: https://test-7923-2-dot-mauthor-dev.ew.r.appspot.com/embed/5456810787995648

2021-04-08 08:25 UTC, tkrassowski requested changes
Nie wiem czy to zamierzone czy nie:
1. Dodaję audio (tekst 2) do multiple gap
2. Wchodzę w przeciągnięte audio
3. Naciskam Enter - czytany jest: Tekst 2, odtwarzane jest audio
4. Podczas odtwarzania naciskam Enter, znowu czytane jest Tekst 2.

2021-04-08 08:25 UTC, tkrassowski commented on addons/multiplegap/src/presenter.js
> +                    voicesArray = voicesArray.concat(presenter.getTextVoicesFromPlaceholder($element));
Chyba nie ma potrzeby tutaj concatować pustej tablicy ze zwrotką z getTextVoicesFromPlaceholder?
A = [];
B = [1,2,3]
A.concat(B) to zawsze będzie zawartość B (a getTextVoicesFromPlaceholder zawsze tworzy nową tablicę, więc nie ma obawy o modyfikacje jakiegos elementu)

2021-04-08 08:25 UTC, tkrassowski commented on addons/multiplegap/src/presenter.js
> +                    var draggableItemValues = $element.attr('draggableitem').split('-');
Widziałbym zawartość tego else w funkcji - żeby wiedzieć jaki to przypadek (readSingleElement?).

2021-04-08 08:25 UTC, tkrassowski commented on addons/multiplegap/src/presenter.js
> +                        if (draggableItemValues.length == 2) {
Żeby zachować spójność: ===

2021-04-08 08:25 UTC, tkrassowski commented on addons/multiplegap/src/presenter.js
> +                if ($element.length == 0) {
Żeby zachować spójność: ===

2021-04-13 08:42 UTC, tkrassowski approved these changes

2021-05-14 09:48 UTC, mgrzelinski reviewed
Na wersji testowej https://test-7923-2-dot-mauthor-dev.ew.r.appspot.com/embed/5456810787995648 po przeniesieniu, za pomocą nawigacji klawiaturowej, MultiAudio2 do multiplegap1, w MultiAudio2 nie wyświetla się _text1_. Czy to jest poprawne zachowanie?

Nawiązując do ostatniego komentarza Agnieszki Marciniak spod ticket'u #7923, w przypadku gdy wsadzimy element MultiAudio2 do multiplegap1, puścimy audio i wciśniemy spacje - element jest usuwany i jest też teraz wyłączany.

2021-05-14 12:31 UTC, maciej-zawlocki-solwit commented
> Na wersji testowej https://test-7923-2-dot-mauthor-dev.ew.r.appspot.com/embed/5456810787995648 po przeniesieniu, za pomocą nawigacji klawiaturowej, MultiAudio2 do multiplegap1, w MultiAudio2 nie wyświetla się _text1_. Czy to jest poprawne zachowanie?
> 
> Nawiązując do ostatniego komentarza Agnieszki Marciniak spod ticket'u #7923, w przypadku gdy wsadzimy element MultiAudio2 do multiplegap1, puścimy audio i wciśniemy spacje - element jest usuwany i jest też teraz wyłączany.

2021-05-14 12:33 UTC, maciej-zawlocki-solwit commented
Zamknięty nieumyślnie, otworzę go ponownie w poniedziałek.

2021-05-14 12:37 UTC, maciej-zawlocki-solwit commented
@mgrzelinski ten "błąd" wynika z tego jak są ustawione cssy w domyślnej templacie. Jak zbadasz element to zobaczysz, że ten tekst tam fizycznie jest.

2021-05-14 13:14 UTC, mgrzelinski submitted a review, later dismissed
Po wyjaśnieniu, brak poprawek.

2021-05-18 08:17 UTC, tkrassowski approved these changes

2021-05-18 08:18 UTC, merged