Added undo-one button in IWB Toolbar, re #7858
icplayer/icplayer pull request #547
Opened 2021-04-22 12:41 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=7858
Wersja testowa: https://test-7858-dot-mauthor-dev.ew.r.appspot.com/present/6743862498295808

2021-04-23 07:15 UTC, rafalzukowski commented on addons/IWB_Toolbar/src/presenter.js
>          presenter.markerDataUrl = presenter.markerCanvas[0].toDataURL('image/png');
Ten kodzik pojawia się wielokrotnie - czy jest szansa go wynieść do funkcji i sensownie nazwać?

2021-05-10 12:42 UTC, tkrassowski requested changes
Przy przełączaniu narzędzi znika narysowana treść:
Rozwijam IWB -> wybieram "Pen" -> Rysuję coś -> zmieniam narzędzie na "Marker" -> znika zawratość.

2021-05-10 12:42 UTC, tkrassowski commented on addons/IWB_Toolbar/src/presenter.js
> +        if (state1.length == 0 || state2.length == 0) {
Widziałbym też tutaj testy tej funkcjonalności.

2021-05-11 11:47 UTC, tkrassowski approved these changes

2021-05-12 07:58 UTC, tkrassowski approved these changes

2021-05-13 09:06 UTC, tkrassowski requested changes
Poprawiłbym tylko to porównywanie stanów, żeby nieco uprościć logikę.

2021-05-13 09:06 UTC, tkrassowski commented on addons/IWB_Toolbar/src/presenter.js
> +        var result = JSON.stringify(newJson1) == JSON.stringify(newJson2);
Tutaj w sumie można by po prostu porównywać wartości kluczów?
```
for (var i = 0; ...) {
  var fieldName = compareFields[i];
  if(json[fieldName] !== json2[fieldName]) {
   return false;
  }
}
return true;```

2021-05-13 09:06 UTC, tkrassowski commented on addons/IWB_Toolbar/src/presenter.js
> +            if (window.savedPanel && window.savedPanel.histories && window.savedPanel.histories[pageIndex]) {
Zastanawiam się czy jest opcja że na stronie będą dwa różne iwbtoolbary.

2021-05-13 09:20 UTC, tkrassowski approved these changes

2021-05-13 11:02 UTC, merged