7991 - (WIP) Limited Gradual Show Answer
icplayer/icplayer pull request #561
Opened 2021-05-31 13:22 UTC by radeksolwit

2021-06-11 11:15 UTC, mdabrowskisolwit commented
Do sprawdzenia limitowanie wyświetlania wyników.
Całość zrobiona na obecnym addonie GradualShowAnswer.
Dodana została opcja worksWith, w której po przekazaniu możemy określić IDki w których modułach chcemy wyświetlać wyniki.
Nieprzekazanie niczego, to działanie tak samo jak do tej pory.
Przykład: https://test-7991-dot-mauthor-dev.ew.r.appspot.com/embed/6040178923667456
Zgodnie z opisem przy przyciskach, mają różne konfiguracje i wyświetlają wyniki przy innych modułach.

2021-06-11 12:46 UTC, tkrassowski requested changes

2021-06-11 12:46 UTC, tkrassowski commented on addons/Gradual_Show_Answer/src/presenter.js
> +            ModelValidators.String("worksWith", {default: ""}),
Tutaj jest jeszcze potrzebny upgrade modelu - w przypadku kiedy do addonu dochodzi nowe property, lekcja która nie jest zedytowana w edytorze będzie miala puste pole, co będzie powodować błąd walidacji
Np. https://test-7991-dot-mauthor-dev.ew.r.appspot.com/embed/5756873712074752 - tutaj przycisk nie działa.
Przykład upgrade'u:
addons/Animation/src/presenter.js::48

```
    presenter.upgradeModel = function (model) {
        var upgradedModel = presenter.addFramesToLabels(model);
        return presenter.upgradeTextToSpeech(upgradedModel);
    };


      presenter.addFramesToLabels = function (model) {
        var upgradedModel = {}, i;
        $.extend(true, upgradedModel, model); // Deep copy of model object

        for (i = 0; i < model["Labels"].length; i++) {
            if (upgradedModel["Labels"][i]["Frames"] == undefined) {
                upgradedModel["Labels"][i]["Frames"] = "";
            }
        }

        return upgradedModel;
    };
```

2021-06-14 07:41 UTC, mdabrowskisolwit commented on addons/Gradual_Show_Answer/src/presenter.js
> +            ModelValidators.String("worksWith", {default: ""}),
Dodane i poprawione, stare addony już działają poprawnie:
https://test-7991-dot-mauthor-dev.ew.r.appspot.com/embed/5756873712074752

2021-06-14 11:23 UTC, maciej-zawlocki-solwit approved these changes

2021-06-16 06:10 UTC, tkrassowski approved these changes

2021-06-16 06:10 UTC, merged