feat(addons): displaying users responds re #8041
icplayer/icplayer pull request #575
Opened 2021-07-16 06:55 UTC by wkarasSolwit

subtask: [https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8041]

2021-07-16 10:41 UTC, maciej-zawlocki-solwit commented on addons/TrueFalse/src/presenter.js
> +        var userAnswers = presenter.printableState['selectedElements'];
Nie masz gwarancji, że printableState będzie. Nie zawsze jest ustawiane.

2021-07-19 06:53 UTC, wkarasSolwit commented on addons/TrueFalse/src/presenter.js
> +        var userAnswers = presenter.printableState['selectedElements'];
poprawione

2021-07-21 11:23 UTC, maciej-zawlocki-solwit commented on addons/TrueFalse/src/style.css
> +.inCorrectAnswerDiv {
incorrect zamiast inCorrect, to jest jedno słowo

2021-07-21 11:24 UTC, maciej-zawlocki-solwit commented on addons/TrueFalse/src/style.css
> +.correctAnswerDiv {
.correctAnswerDiv:after, albo :before. Inaczej content nie działa

2021-07-21 11:30 UTC, maciej-zawlocki-solwit commented
Wygląda mi na to tak, jakbyś założył, że mogą być tylko dwie odpowiedzi. Może być ich więcej i w tym momencie drukowanie ze stanem zaczyna ci wybuchać. Odpowiedzi do wyboru są definiowane w property "Choices"

2021-07-21 11:30 UTC, maciej-zawlocki-solwit commented
W showAnswer+State tytuły kolumn rozjeżdżają się z kolumnami, trzeba w komórkach header (wszystkich albo ostatniej, zależnie od isMulti) dodać colspan=„2”

2021-07-21 11:31 UTC, maciej-zawlocki-solwit requested changes

2021-07-21 11:31 UTC, maciej-zawlocki-solwit commented on addons/TrueFalse/src/presenter.js
> +        function getUserRespond() {
responses, nie respond

2021-07-21 11:35 UTC, maciej-zawlocki-solwit commented
A, i wystaw wersję testową i wstaw link do niej w tym PRze

2021-07-23 05:41 UTC, maciej-zawlocki-solwit requested changes

2021-07-23 05:41 UTC, maciej-zawlocki-solwit commented on addons/TrueFalse/src/presenter.js
> +
1) daj te funkcje poza getPrintableHTML
2) teraz to dopiero zauważyłem, ale dobrze by było wyzerować presenter.printableState na samym końcu. Aktualnie jeżeli puści się drukowanie najpierw ze state'em, a potem bez, to za drugim razem nadal będzie korzystał ze state'a.
Reszta wygląda ok

2021-07-28 05:46 UTC, maciej-zawlocki-solwit approved these changes

2021-07-28 06:16 UTC, merged