test-7893 Add documentation for gradual show answers
icplayer/icplayer pull request #577
Opened 2021-07-20 06:41 UTC by rpiotrowski-solwit

ticket:
https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?tickets_report_id=filter:0&ticket=7893
Documentation:
https://www.mauthor.com/doc/en/page/Gradual-Show-Answers
demo lesson:
https://www.mauthor.com/embed/5253547551227904

2021-07-21 12:56 UTC, maciej-zawlocki-solwit requested changes

2021-07-21 12:56 UTC, maciej-zawlocki-solwit commented on addons/Gradual_Show_Answer/documentation.md
> +[Demo presentation](/embed/5253547551227904 "Demo presentation") contains examples of how to use the Gradual Show Answers addon.
przykłady powinny być na samym końcu

2021-09-03 10:07 UTC, rpiotrowski-solwit commented
@maciej-zawlocki-solwit proszę o approve

2021-09-03 10:38 UTC, maciej-zawlocki-solwit approved these changes

2022-03-25 07:52 UTC, merged