Test 8051 GSA - Text Coloring
icplayer/icplayer pull request #597
Opened 2021-08-02 09:57 UTC by rwojdak

2021-08-05 05:39 UTC, maciej-zawlocki-solwit requested changes
Po włączeniu trybu gradual show answers addon się nie blokuje, nadal możliwe jest wybieranie kolorów i zaznaczanie odpowiedzi. Podobnie jak z Show Answers, w momencie uruchomienia trybu GSA powinno to zostać zablokowane.

2021-08-16 07:14 UTC, rpiotrowski-solwit approved these changes
Wszystko w porządku.

2021-08-16 07:14 UTC, rpiotrowski-solwit commented on src/main/java/com/lorepo/icplayer/public/libs/dictionaries/fr/dictionary.js
> +	"Text_Coloring_property_show_all_answers_in_gradual_show_answers_mode": "Show all answers in gradual show answers mode",
wcięcie, wizualna poprawka

2021-08-16 07:17 UTC, rpiotrowski-solwit requested changes
Brakuje wzmianki w dokumentacji odnośnie nowego property

2021-08-16 07:21 UTC, rpiotrowski-solwit reviewed
Brakuje wzmianki w changelog.txt

2021-08-18 08:23 UTC, maciej-zawlocki-solwit requested changes

2021-08-18 12:49 UTC, rwojdak commented on addons/Commons/src/statefull-addon-object.js
> +        gradualShowAnswersWorkState: function gradualShowAnswersWorkState () {
To znaczy problemem w przypadku addonu Text_Coloring jest to, że w funkcji presenter.onEventReceived korzysta on właśnie z funkcji zaczerpniętych z pliku statefull-addon-object.js i nie widziałem innego sposobu na obejście tego. Mogę ewentualnie przerobić addon Text_Coloring w taki sposób, aby (tak jak to robią pozostałe addony), korzystał z wbudowanych w siebie funkcji (typu presenter.showAnswers() zamiast presenter.stateMachine.showAnswers()). Napisanie tego zajmie co prawda trochę czasu (będzie trzeba niemal zacząć zadanie od początku), ale dzięki temu będzie on napisany w taki sposób jak pozostałe addony, a jako że wiem jak to wszystko wygląda, to praca ta będzie trwała krócej niż pisanie tego po raz pierwszy.

2021-09-01 11:53 UTC, maciej-zawlocki-solwit approved these changes

2021-09-03 05:42 UTC, merged