feat(addons): Text Coloring print handling
icplayer/icplayer pull request #600
Opened 2021-08-02 14:21 UTC by wkarasSolwit

[Link do zadania](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=7914)
[Link do wersji testowej](https://test-7914-v1-dot-mauthor-dev.ew.r.appspot.com/embed/5009099907399680)

2021-08-17 08:31 UTC, maciej-zawlocki-solwit commented
różnice między kolorami wydają mi się mało "wyraziste", trudno jest mi odróżnić jeden od drugiego

2021-08-17 08:33 UTC, maciej-zawlocki-solwit commented
Nie sprawdzasz, w jakim trybie działa addon. Tam jest property mode, od którego zależy, czy możliwe do pokolorowania będą wszystkie słowa, czy tylko te, które "trzeba". Ty w zwykłym trybie (bez stanu i bez odpowiedzi) zawsze podkreślasz tak, jakbyś był w tym drugim trybie.

2021-08-17 08:33 UTC, maciej-zawlocki-solwit commented
Brak legendy, nie wiem, czy powinna być czy nie?

2021-08-17 08:33 UTC, maciej-zawlocki-solwit requested changes

2021-08-17 08:33 UTC, maciej-zawlocki-solwit commented on addons/Text_Coloring/src/presenter.js
> +        model = presenter.upgradeModel(model);
Zamiast pracować bezpośrednio na modelu skorzystaj z validateModel i presenter.configuration (zobacz jak to drugie jest tworzone wyżej w kodzie).

2021-08-19 05:14 UTC, maciej-zawlocki-solwit approved these changes

2021-08-31 09:43 UTC, karol-f-solwit commented on addons/Text_Coloring/src/presenter.js
> +        var legendTitle = model['Legend title'] ?  model['Legend title'] : 'Legend';
Tutaj można zastosować taki zapis: 
`var legendTitle = model['Legend title'] || 'Legend';`
Nie potrzebna jest zmiana ale FYI na przyszłość :D

2021-08-31 09:50 UTC, karol-f-solwit commented on addons/Text_Coloring/src/presenter.js
> +        var didUserAnswer = userAnswer ? userAnswer.some(answer => answer.isSelected) : false;
Tu też można użyć skróconego zapisu, nie do poprawy, ale po prostu fyi
didUserAnswer = !!userAnswer && userAnswer.some(answer => answer.isSelected)

2021-08-31 09:51 UTC, karol-f-solwit commented on addons/Text_Coloring/src/presenter.js
> +        var areAllSelectable = presenter.configuration.mode === 'ALL_SELECTABLE'
Średnik 😉

2021-08-31 10:06 UTC, karol-f-solwit commented on addons/Text_Coloring/test/PrintHTMLTest.js
> +    'test given user answers and showAnswer on false when getPrintableHTML was called should wrap underscore word': function () {
Zmieniłbym 'test should..." i "test given ... when ... should" na konwencję given when then, ale to również pierdoła.

2021-08-31 10:06 UTC, karol-f-solwit submitted a review, later dismissed
Są drobne poprawki w kwestii estetycznej, ale moim zdaniem nie wymagają poprawy i można puścić dalej.

2021-09-01 12:29 UTC, wkarasSolwit commented
Jeżeli wyżej wymienione poprawki nie są wstrzymujące, PR przekazuję do testów akceptacyjnych

2021-09-01 12:30 UTC, karol-f-solwit commented
@wkarasSolwit Ok - można do RFAccTest

2021-09-15 10:57 UTC, merged