Add functionality to extract lesson titles from Printable Controller, re #8075
icplayer/icplayer pull request #607
Opened 2021-08-06 07:24 UTC by msawoniuk

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/8075-dodanie-funkcjonalno%C5%9Bci-wyci%C4%85ganie-tytu%C5%82%C3%B3w-lekcji-z-printable-cont/details
Ticket główny: https://learneticsa.assembla.com/spaces/lorepo/tickets/7915-dodanie-wsparcia-dla-drukowania-w-addonie-hierarchical-lesson-report/details
Wersja testowa: https://test-8075-dot-mauthor-dev.ew.r.appspot.com
Lekcja testowa:https://test-8075-dot-mauthor-dev.ew.r.appspot.com/embed/5419668984561664

Zmiany w addonie HLR dodałem aby pokazać czy faktycznie tytuły lekcji są przekazywane.
Zmiany w addonie są związane z ticketem głównym i jego innych subtaskami.
Testów nie pisałem, przez problem z testowaniem obiektu JS w javie. Prosiłbym o wycenę czy potrzebne są testy.

2021-08-18 06:03 UTC, maciej-zawlocki-solwit requested changes
Zwróć dodatkowo uwagę na to, że zarówno w score jak i w contentInformation dostajesz null, jeżeli uruchomisz je w edytorze (przycisk print preview oraz rozwijany z jego dropdown'u lesson preview). W wypadku score'a to oczywiste, ale sprawdziłbym, czy nie uda ci się uzyskać contentInformation w edytorze. Jeśli nie, to trudno, ale jako minimum trzebaby upewnić się, że addon będzie się prawidłowo wyświetlał pomimo null'i (być jakieś placeholder'y, jak w "normalnym" preview tego addonu?).

2021-08-23 07:00 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/public/libs/commons.js
> -(function(f){function a(a){return{isValid:!1,errorCode:a,value:void 0}}function b(a){return{isValid:!0,value:a,errorCode:""}}function d(a){return"function"!=typeof/./&&"object"!=typeof Int8Array&&"fu
Mój błąd, zmiany zostaną wyrzucone

2021-08-23 07:00 UTC, msawoniuk commented on addons/Hierarchical_Lesson_Report/src/presenter.js
> +        console.log("Score: ", score);
Tak, taki był zamysł.

2021-09-07 13:19 UTC, rwojdak approved these changes

2021-09-08 06:48 UTC, merged