8070 crossword gsa
icplayer/icplayer pull request #609
Opened 2021-08-10 10:49 UTC by jedrzejniemiera

Ticket:
https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8070

Wersja testowa:
https://test-8070-dot-mauthor-dev.ew.r.appspot.com

2021-08-18 06:44 UTC, maciej-zawlocki-solwit reviewed
2) nie blokujesz edycji addonu w trybie gradual show answers.
3) W trybie gradual show answers odkryte odpowiedzi są traktowane jako prawidłowe. Dodaj w lekcji addon Page Score, upewnij się że strona ma zaznaczone property isReportable (w edytorze klikasz gdziekolwiek na stronie poza addonami i prawej wyświetlą ci się propertiesy). Żeby to rozwiązać zmodyfikuj metodę getScore tak, żeby przed obliczaniem wyniku, jeśli jesteś w gradual show answer, to był on wyłączany, a następnie ponownie włączany po zakończeniu obliczeń.

2021-08-18 06:44 UTC, maciej-zawlocki-solwit commented on addons/crossword/src/presenter.js
> +                        orientation: orientation,
Zamiast bawić się string'ami zamieniłbym orientation na isHorizontal z wartością typu boolean.

2021-08-25 07:36 UTC, rpiotrowski-solwit requested changes
Pamiętaj proszę o uzupełnieniu dokumentacji oraz dodanie upgradeModel do kodu,
Przykłady:
https://github.com/icplayer/icplayer/pull/597/files#diff-b287d68c3d4372b9b6b564d11797a1cf1eb44e8455798e4457742ac0eba450ddR682

https://github.com/icplayer/icplayer/pull/614

2021-08-25 07:36 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +    presenter.score = 0;
dodać nowe property showAllAnswersInGradualShowAnswersMode i obsługę dla addonu crossword, dodanie labelki w dictionaries

2021-08-25 07:36 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +        } else if (eventName === "GradualHideAnswers") {
Gradual hide Answer nie resetuje licznika GSA:
https://test-8070-dot-mauthor-dev.ew.r.appspot.com/embed/5679711671812096

2021-08-25 07:36 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
>  }
brak nowej lini

2021-08-25 07:36 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +        if (presenter.wordNumbersHorizontal || presenter.wordNumbersVertical) {
Chowanie odpowiedzi użytkownika powinno odbywać się w momencie gdy GSA odkrywa dane słowo

2021-08-25 07:36 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +    presenter.getActivitiesCount = function() {
Musi zwracać 1 w momencie gdy showAllAnswersInGradualShowAnswersMode jest włączony

2021-09-03 07:59 UTC, maciej-zawlocki-solwit requested changes

2021-09-03 07:59 UTC, maciej-zawlocki-solwit commented on addons/crossword/src/presenter.js
> +            var events = ['ShowAnswers', 'HideAnswers', 'GradualShowAnswers', 'GradualHideAnswers'];
przenieś proszę ustawianie event handlerów do oddzielnej metody.

2021-09-03 07:59 UTC, maciej-zawlocki-solwit commented on addons/crossword/src/presenter.js
> +        var upgradedModel = {};
poprosiłbym, żebyś tą logikę przeniósł do oddzielnej metody, którą będziesz wywoływał w upgradeModel. Wiem, że wtedy masz metodę która jedyne co robi, to wywołuje inną metodę, ale byłoby to zrobione pod przyszłe propertiesy, oraz żeby być spójnym z rozwiązaniami z innych addonów.

2021-09-03 10:31 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +            var events = ['ShowAnswers', 'HideAnswers', 'GradualShowAnswers', 'GradualHideAnswers'];
Niew wiem czemu ale przeniesienie ustawienie event handlerów powoduje nieprawidłowe działanie GradualHideAnswers.
pierwszy element krzyżówki nie chce się wtedy zresetować

2021-09-03 10:39 UTC, rpiotrowski-solwit commented on addons/crossword/src/presenter.js
> +            var events = ['ShowAnswers', 'HideAnswers', 'GradualShowAnswers', 'GradualHideAnswers'];
dobra naprawiłem

2021-09-07 14:47 UTC, karol-f-solwit commented on addons/crossword/src/presenter.js
> +    presenter.prepareCorrectAnswers = function() {
Nie chciała by ta funkcja być otestowana? W przyszłości wprowadzenie zmian i czytanie kodu może nie być takie oczywiste, a jakby takie testy były, to jest czarno na białym czego od tej funkcji oczekujemy :)

2021-09-09 10:19 UTC, karol-f-solwit approved these changes

2021-09-15 10:49 UTC, merged