feat(addons): Clock handling gradual show answers re $8083
icplayer/icplayer pull request #610
Opened 2021-08-10 11:26 UTC by wkarasSolwit

[Link do zadania](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8083)
[Link do wersji testowej](https://test-8083-v1-dot-mauthor-dev.ew.r.appspot.com/embed/5714587175354368)

2021-08-13 12:17 UTC, jedrzejniemiera requested changes

2021-08-13 12:17 UTC, jedrzejniemiera commented on addons/Clock/src/presenter.js
> +                presenter.isGradualShowAnswersActive = true;
Obsługując event powinieneś sprawdzić czy funkcja GSA na pewno poszukuje konkretnie tego addonu w danej chwili. Inaczej, jeśli jest jakiś addon który GSA powinno obsłużyć przed Clock, to te dwa addony pokażą swoją odpowiedź jednocześnie, co się mija z założeniem GSA. Spójrz na ten przykład: 
https://test-8083-v1-dot-mauthor-dev.ew.r.appspot.com/embed/4841954720350208

Tutaj masz kod z innego addonu który działa: 
`presenter.onEventReceived = function (eventName, data) {

        if (!presenter.isModelValid) return;

        if (eventName === "ShowAnswers") {

            presenter.showAnswers();

        } else if (eventName === "HideAnswers") {

            presenter.hideAnswers();

        } else if (eventName === "GradualShowAnswers") {

            if (!presenter.isGradualShowAnswersActive) {

                presenter.isGradualShowAnswersActive = true;

            }

            if (data.moduleID === presenter.addonID) {

                presenter.gradualShowAnswers(parseInt(data.item, 10));

            }

        } else if (eventName === "GradualHideAnswers") {

            presenter.isGradualShowAnswersActive = false;

            presenter.hideAnswers();

        }

    };`

2021-08-13 12:17 UTC, jedrzejniemiera commented on addons/Clock/test/HandleEventsTests.js
> +    'test should invoke showAnswer and change isGradualShowAnswersActive when GradualShowAnswers event was showed': function () {
Będzie to też wymagało dodania data.moduleID w tym teście

2021-08-18 07:51 UTC, rpiotrowski-solwit requested changes

2021-08-18 08:07 UTC, rpiotrowski-solwit commented
Jest jeszcze jeden błąd, który należałoby poprawić w działaniu tego addonu. Chodzi tutaj o funkcjonowanie showAnswers przy użyciu Clock w customowej lekcji:
https://test-8083-dot-mauthor-dev.ew.r.appspot.com/embed/4659481248006144#40

Przycisk show answer nie powoduje pokazania odpowiedzi dla addonu clock na dole ekranu z racji, że od razu po wywołaniu ShowAnswer wywołane są metody:
**getScore, getMaxScore, getErrorCount**
Które wywołują event Hide answer
![image](https://user-images.githubusercontent.com/79642842/129861448-e3cd99d9-2ca6-45f5-9d0a-93d604e0792f.png)

Rozwiązanie jak poprawić ten błąd znajduje się w tickecie:
https://learneticsa.assembla.com/spaces/lorepo/tickets/7709--great%7Cpearson--nie-dzia%C5%82a-show-answers-dla-crossword-gdy-jest-controller/details?comment=1692152523

2021-08-24 09:26 UTC, rpiotrowski-solwit approved these changes

2021-08-25 11:09 UTC, merged