Test-8084: GSA - Coloring
icplayer/icplayer pull request #611
Opened 2021-08-11 14:41 UTC by rwojdak

2021-08-16 08:54 UTC, rpiotrowski-solwit requested changes
Brakuje zmiany w changelog.txt

Błąd w funkcjonowaniu showAllAnswersInGSAMode gdy mamy kilka takich addonów pod getActivitiesCount prawododobnie zwraca złą wartość, ponieważ trzeba klikać wiele razy aby odkrywanie dalszych odpowiedzi się kontynuowało. Przykład:
https://test-8084-dot-mauthor-dev.ew.r.appspot.com/embed/6243853814202368

2021-08-17 09:22 UTC, rwojdak commented
Poprawki wdrożone. Wstawiłem przy okazji changelog na GSA do pozostałych addonów, które zrobiłem, bo tam również nie wprowadzałem logów

2021-08-17 12:57 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2021-08-18 08:16 UTC, rpiotrowski-solwit approved these changes

2021-08-25 11:02 UTC, merged