Test-7699: Show answers changes score in hangman addon
icplayer/icplayer pull request #619
Opened 2021-08-18 08:07 UTC by rwojdak

2021-08-18 12:28 UTC, maciej-zawlocki-solwit approved these changes

2021-09-01 12:56 UTC, wkarasSolwit submitted a review, later dismissed
Zostawiam jedną uwagę - estetyczną nie wpływającą na funkcjonalność.

2021-09-03 06:11 UTC, maciej-zawlocki-solwit requested changes
Jeżeli modyfikujesz states.phrases (dodając nowe pole), to musisz też zmodyfikować presenter.setState. Po pierwsze, nie jest tam uwzględniony endOfGame. Co więcej, nie masz gwarancji, że stan który otrzymasz w tej metodzie, był utworzony korzystając z najnowszej wersji player'a, więc może nie mieć nowego pola. W związku z tym należy dodać metodę upgradeState, która przyjmie stan, sprawdzi czy ma on endOfGame, a jeśli nie, ustawi w nim odpowiednią wartość.

2021-09-08 08:57 UTC, rpiotrowski-solwit approved these changes

2021-09-09 07:46 UTC, merged