feat(addon): Dodanie show i hide do addonu Hierarchical TOC re #8044
icplayer/icplayer pull request #625
Opened 2021-08-23 08:14 UTC by karol-f-solwit

Wersja testowa: https://test-8044-dot-mauthor-dev.ew.r.appspot.com
Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/8044-hierarchical-table-of-contents---dodanie-show-i-hide/details#

2021-08-30 08:28 UTC, wkarasSolwit approved these changes

2021-09-10 11:52 UTC, wkarasSolwit requested changes

2021-09-15 07:35 UTC, karol-f-solwit commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        presenter.setVisibility(presenter.configuration.isVisible);
Nie. Tutaj jest specjalnie configuration.isVisible, ponieważ po resecie chcemy ustawić wersję jaka była pierwotnie, stąd też rozdzieliłem na isVisible i configuration.isVisible. Jedno ma pamiętać stan aktualny (przy zmianie stron, etc) a drugie ma pamiętać z jakim stanem addon był wczytywany.

2021-09-15 07:36 UTC, karol-f-solwit commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        if (presenter.isVisible !== undefined) {
Zastosowano :)

2021-09-21 06:06 UTC, maciej-zawlocki-solwit requested changes

2021-09-21 06:06 UTC, maciej-zawlocki-solwit commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +            presenter.setVisibility(presenter.isVisible);
Po pierwsze, skoro to jest metoda initialize, to wątpię, żeby ten warunek był kiedykolwiek spełniony. Sprawdź to proszę i usuń jeśli jest zbędne. Po drugie, należałoby zdefiniować property isVisible na początku pliku razem z innymi zmiennymi, zamiast go tworzyć wewnątrz setVisibility. Przy okazji rozwiązuje to też problem konieczności sprawdzenia, czy presenter ma to property (gdyby się okazało, że ten warunek jest jednak potrzebny, możesz dać domyślnie wartość null dla isVisible, żeby można było rozróżnić czy już było ustawione czy nie).

2021-09-27 10:55 UTC, wkarasSolwit submitted a review, later dismissed
brak poprawek

2021-09-28 11:46 UTC, wkarasSolwit approved these changes
bez poprawek

2021-10-04 10:52 UTC, merged