Create Flash Cards tests #8108
icplayer/icplayer pull request #632
Opened 2021-08-26 07:55 UTC by wkarasSolwit

[Link do zadania](https://app.assembla.com/spaces/lorepo/tickets/8108-create-flashcard-tests/details#)

2021-09-03 11:15 UTC, maciej-zawlocki-solwit requested changes

2021-09-03 11:15 UTC, maciej-zawlocki-solwit commented on addons/FlashCards/test/HandlingCardsFunctionTests.js
> +        this.view = "<div class=\"flashcards-wrapper\">" +
Tzn. w mojej opinii  może zostać, jeżeli tak trzeba żeby się dało testować w miarę sensownie, ale pod warunkiem że to będzie element html, bo teraz to jest zwykły string.

2021-09-10 10:27 UTC, wkarasSolwit commented on addons/FlashCards/test/HandlingCardsFunctionTests.js
> +        this.view = "<div class=\"flashcards-wrapper\">" +
Powyższy tekst zawierający cały szablon HTML jest niezbędny - jego brak zatrzymuje inicjalizację, co wstrzymuje resztę testów. W metodzie init addonu przekazany tekst jest owijany przez jQuery i już konkretnie ten obiekt jest przetwarzany.

2021-09-14 07:39 UTC, rpiotrowski-solwit commented on addons/FlashCards/test/HandlingCardsFunctionTests.js
> +        this.view = "<div class=\"flashcards-wrapper\">" +
@wkarasSolwit wydaje mi się, że Maćkowi chodziło o coś takiego co robiliśmy z Michałem w przypadku testowania drukowalnych wersji addonu czyli tworzenie obiektu htmlowego przy użyciu jquery:
https://github.com/icplayer/icplayer/pull/548/files#diff-7b6883abc1d956394b47e3be16027764cb72e0b01de33f55c2c7b6a9d19c3b57R295

Co do samych testów nie znalazłem nigdzie testu funkcji 'displayCard', która posiada najwięcej zależności

2021-09-22 11:51 UTC, rpiotrowski-solwit submitted a review, later dismissed

2021-09-22 11:54 UTC, rpiotrowski-solwit commented
Trochę duplikacji kodu w tych 2 testach jeśli chodzi o inicjalizację tego htmla ale jeśli nie da się tego wyciągnąć do jednej funkcji to może być.

2021-09-27 10:10 UTC, rpiotrowski-solwit approved these changes

2021-11-29 08:42 UTC, merged