Test-8129: Fix linguistic errors in keyboard navigation of polish version of quiz
icplayer/icplayer pull request #650
Opened 2021-09-17 14:58 UTC by rwojdak

2021-09-21 07:12 UTC, maciej-zawlocki-solwit requested changes
Generalnie większość tego kodu powinieneś przenieść do utils'a TTS (addons/Commons/tts-utils.js )

2021-09-21 07:12 UTC, maciej-zawlocki-solwit commented on addons/Quiz/src/presenter.js
> +        if (['pl', 'polish'].includes(language.toLowerCase()))
uwzględnij jeszcze "pl-PL" ( oczywiście małymi literami).

2021-09-21 07:12 UTC, maciej-zawlocki-solwit commented on addons/Quiz/src/presenter.js
> +        var language = presenter.config.langTag;
speech texty zawsze korzystają z języka lekcji, a nie z języka modułu. Korzystaj od razu z document.documentElement.lang .

2021-10-06 08:19 UTC, wkarasSolwit approved these changes
uwagi estetyczne - nie blokujące

2021-10-06 08:19 UTC, wkarasSolwit commented on addons/Commons/src/tts-utils.js
> +            textUnits.forEach(function(element, index, array) {
spróbował bym wynieść ten kod:
 textTeens.forEach(function(element, index, array){
                array[index] = this._simpleChangePolishWordGender(element, gender);
}.bind(this));
do funkcji z parametrem array, która nadpisuje stan przekazanego array

2021-10-06 08:19 UTC, wkarasSolwit commented on addons/Commons/src/tts-utils.js
> +            if (ordinalPartLength === 1)
uwaga estetyczna:
można by skorzystać z konstrukcji switch / case:
switch(true) {
case (ordinalPartLength === 1):
(...)
case (ordinalPartIsTeens && ordinalPartLength === 2):
(...)
case (ordinalPartLength === 2):
(...)
case (ordinalPartLength === 3):
(...)
case ordinalPartIsUnits:
(...)
case ordinalPartIsTeens:
(...)
case ordinalPartIsTens:
(...)
case ordinalPartIsHundreds:
(...)
default:
(..)

2021-10-12 07:19 UTC, merged