Filled Gap fix malfunction of the reset method
icplayer/icplayer pull request #660
Opened 2021-09-27 08:20 UTC by wkarasSolwit

[Link do zadania](https://app.assembla.com/spaces/lorepo/tickets/8150-filled-gap---malfunction-of-the-reset-method/details?tab=activity)

2021-09-27 14:29 UTC, msawoniuk requested changes

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextPresenter.java
> +            child.setResetStatus(true);
Ten fragment kodu nie dawał mi spokoju po naszej rozmowie. Jestem obecnie na Twej gałęzi i przeniosłem child.setResetStatus(true); do reset() w GapWidget i działa.
```
@Override
	public void reset() {
		setText("");
		gapInfo.setResetStatus(true);
		this.setWorkMode();
	}
``` 
Zrobiłem to z dwóch powodów:
* intuicyjne jest to, że w resecie zmienia się status czy wykonał się reset - zwiększenie czytelności i zrozumienia kodu
* w więcej niż w tym fragmencie kodu wykonywana jest operacja reset na child. Przykładem jest `handleGradualHideAnswers`. Więc, przy każdym reset musiałbyś wykonać metodę setResetStatus aby nie powodować niejednoznaczności w stanie wasReset dla obecnego kodu.

Więc należy dodać moją propozycję lub wykonać setResetStatus w reszcie powiązanego kodu.

Testów nie puszczałem, więc prosiłbym abyś wprowadził tą zmianę a następnie przetestował bo mogłem coś przegapić/źle zrozumieć.

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextPresenter.java
> +            child.setResetStatus(true);
W nawiązaniu do naszej rozmowy należy ustawić odpowiednie wcięcie

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/AudioButtonWidget.java
> +	public boolean getResetStatus() {
W nawiązaniu do naszej rozmowy należy ustawić odpowiednie wcięcie

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/DraggableGapWidget.java
> +    @Override
W nawiązaniu do naszej rozmowy należy ustawić odpowiednie wcięcie

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/AudioButtonWidget.java
> +        // 	not implement
W nawiązaniu do naszej rozmowy należy zmienić nazwę komentarza na `TODO not implement`

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/AudioButtonWidget.java
>          if (focus) {
W nawiązaniu do naszej rozmowy należy zmienić nazwę komentarza na `TODO not implement`

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/InlineChoiceWidget.java
> +// 		return choiceInfo.getResetStatus();
W nawiązaniu do naszej rozmowy należy zmienić nazwę komentarza na `TODO not implement`

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/InlineChoiceWidget.java
> +// 		choiceInfo.setResetStatus(wasReset);
W nawiązaniu do naszej rozmowy należy zmienić nazwę komentarza na `TODO not implement`

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/InlineChoiceWidget.java
> +    @Override
W nawiązaniu do naszej rozmowy należy ustawić odpowiednie wcięcie

2021-09-27 14:29 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/TextPresenter.java
> +            child.setResetStatus(true);
Tutaj dodam komentarz abyś mógł go po poprawieniu zamknąć.
Brakuje informacji o wprowadzonej zmianie w changelog.txt

2021-09-28 10:11 UTC, karol-f-solwit approved these changes

2021-10-01 12:15 UTC, maciej-zawlocki-solwit approved these changes

2021-11-29 09:34 UTC, maciej-zawlocki-solwit approved these changes

2021-11-29 09:34 UTC, merged