Coloring and Figure Drawing - removing only wrong answers #8263
icplayer/icplayer pull request #706
Opened 2022-01-24 09:09 UTC by wkarasSolwit

[Link do zadania](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8263)
[Link do wersji testowej](https://test-8263-dot-mauthor-dev.ew.r.appspot.com)
[Link do przykładowej lekcji](https://test-8263-dot-mauthor-dev.ew.r.appspot.com/embed/5638077332586496)

2022-02-02 14:34 UTC, karol-fischbach-solwit commented on addons/FigureDrawing/src/presenter.js
> +        console.log('Run - view', view)
Logi

2022-02-02 15:03 UTC, karol-fischbach-solwit requested changes
Logi na pewno do usunięcia.
Drugi komentarz wedle uznania.

2022-02-09 07:57 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2022-02-16 09:56 UTC, karol-fischbach-solwit submitted a review, later dismissed

2022-02-18 13:57 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2022-02-22 10:26 UTC, merged