feat(addon): Added Second Hand to Addon Clock re #8270
icplayer/icplayer pull request #713
Opened 2022-02-09 11:37 UTC by karol-fischbach-solwit

Wersja testowa: https://test-8270-dot-mauthor-dev.ew.r.appspot.com/
Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/8270--support--porto-editora---dodanie-wskaz%C3%B3wki-sekundowej-do-modu%C5%82u-clock/details#

2022-02-11 14:39 UTC, wkarasSolwit requested changes
Kilka uwag - do sprawdzenia

2022-02-11 14:39 UTC, wkarasSolwit commented on addons/Clock/src/presenter.js
> +            if (value % step == 0) {
można skrócić zapis do:
return value % step === 0;

2022-02-11 14:39 UTC, wkarasSolwit commented on changelog.txt
> -2021-12-20 Change audio format from wav to mp3 in MediaRecorder addon
usunięty wpis - celowo?

2022-02-14 15:26 UTC, karol-fischbach-solwit commented on addons/Clock/src/presenter.js
> +        return (
Wydzielałem z istniejącego rozwiązania, żeby użyć gdzie indziej, dużo kodu się powtarzało, przeoczenie ;)

2022-02-14 15:26 UTC, karol-fischbach-solwit commented on changelog.txt
> -2021-12-20 Change audio format from wav to mp3 in MediaRecorder addon
Tak, ktoś machnął błąd przy mergowaniu i zauważ, że data się nie zgadza. Dodatkowo ten wpis jest zdublowany, jest również niżej w poprawnej kolejności czasowej.

2022-02-16 08:06 UTC, wkarasSolwit submitted a review, later dismissed
OK

2022-02-18 12:07 UTC, wkarasSolwit approved these changes
OK

2022-03-01 12:00 UTC, merged