Automatic feedback, re #8279
icplayer/icplayer pull request #718
Opened 2022-02-18 13:27 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8279
Wersja testowa: https://test-8279-dot-mauthor-dev.ew.r.appspot.com/embed/5638989778255872

2022-02-24 13:43 UTC, karol-fischbach-solwit commented on addons/Automatic_Feedback/test/ModelValidationTest.js
> +    'test given model with only default feedavks when validation was called then return configuration with default feedbacks set': function () {
feedavks = feedbacks?

2022-02-24 14:36 UTC, karol-fischbach-solwit requested changes
Jak rozmawialiśmy.
1. Błąd w przypadku innej opcji niż popup.
2. Wymagany podwójny klik przy pisaniu w gapie.
3. Mała literówka w teście.
Po za tym, wszystko ok.

2022-02-25 15:26 UTC, karol-fischbach-solwit reviewed
Mała poprawka albo nie. Do przegadania?

2022-03-02 12:17 UTC, karol-fischbach-solwit commented on addons/Automatic_Feedback/src/presenter.js
> +            if (!presenter.configuration.displayMode === DISPLAY_MODES.BLOCK || presenter.configuration.displayFeedbackButtons) {
Negacja warunku powinna ujmować porównanie w nawiasie. To samo w linijce 206

2022-03-02 13:02 UTC, karol-fischbach-solwit submitted a review, later dismissed

2022-03-14 07:15 UTC, wkarasSolwit approved these changes
OK

2022-03-14 07:36 UTC, wkarasSolwit requested changes
do poprawy

2022-03-31 13:49 UTC, karol-fischbach-solwit approved these changes

2022-04-01 08:43 UTC, merged