Test 8324
icplayer/icplayer pull request #736
Opened 2022-03-31 13:02 UTC by karol-fischbach-solwit

Wersja testowa: 
Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/8324--tts--editable-window/details?tab=activity#

2022-04-05 07:12 UTC, wkarasSolwit requested changes
Drobne uwagi

2022-04-05 07:12 UTC, wkarasSolwit commented on addons/EditableWindow/src/presenter.js
> +    EditableWindowKeyboardController.prototype.getTarget = function (element, willBeClicked) {
nieużyty parametr 'willBeClicked'

2022-04-05 07:12 UTC, wkarasSolwit commented on addons/EditableWindow/src/presenter.js
> +        let element = this.getTarget(this.keyboardNavigationCurrentElement, true);
wydaje mi się, że 'const' będzie adekwatniejsze

2022-04-05 07:12 UTC, wkarasSolwit commented on addons/EditableWindow/src/presenter.js
> +        let element = this.getTarget(this.keyboardNavigationCurrentElement, true);
dłuższe fragmenty kodu z bloków if / else (4-5l inii) wyniósłbym do osobnych funkcji

2022-04-05 07:12 UTC, wkarasSolwit commented on addons/EditableWindow/src/presenter.js
> +            let key = presenter.getTTSKeyBasedOnColor(element);
'const' key

2022-04-05 07:12 UTC, wkarasSolwit commented on addons/EditableWindow/src/presenter.js
> +        let element = this.getTarget(this.keyboardNavigationCurrentElement, false);
'const' element

2022-04-08 10:13 UTC, karol-fischbach-solwit commented on addons/EditableWindow/src/presenter.js
> +    EditableWindowKeyboardController.prototype.getTarget = function (element, willBeClicked) {
Poprawione, oryginalnie getTarget używa tych dwóch argumentów więc chciałem być zgodny, ale faktycznie chyba sensowniej bez zbędnego argumentu.

2022-04-08 10:14 UTC, karol-fischbach-solwit commented on addons/EditableWindow/src/presenter.js
> +        let element = this.getTarget(this.keyboardNavigationCurrentElement, true);
Done

2022-04-08 10:15 UTC, karol-fischbach-solwit commented on addons/EditableWindow/src/presenter.js
> +            let key = presenter.getTTSKeyBasedOnColor(element);
Done

2022-04-08 10:15 UTC, karol-fischbach-solwit commented on addons/EditableWindow/src/presenter.js
> +        let element = this.getTarget(this.keyboardNavigationCurrentElement, false);
Done

2022-04-11 06:03 UTC, maciej-zawlocki-solwit approved these changes

2022-04-28 13:19 UTC, maciej-zawlocki-solwit approved these changes

2022-05-06 07:21 UTC, merged