Adding keyboard naviation and speech text to Audio Playlist 8323
icplayer/icplayer pull request #758
Opened 2022-05-11 13:30 UTC by wkarasSolwit

[Zadanie](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8323)
[Wersja testowa](https://test-8323-dot-mauthor-dev.ew.r.appspot.com)
[Lekcja testowa](https://test-8323-dot-mauthor-dev.ew.r.appspot.com/embed/4765525970255872)

2022-05-16 10:57 UTC, maciej-zawlocki-solwit approved these changes

2022-05-19 14:14 UTC, Michal-sw-solwit approved these changes
Ogólna logika OK, parę sugestii stylistycznych

2022-05-19 14:14 UTC, Michal-sw-solwit commented on addons/AudioPlaylist/src/presenter.js
> +            var percent = Math.round(volume * 100);
Jak wyżej odnośnie podgłaśniania/ściszania

2022-05-19 14:14 UTC, Michal-sw-solwit commented on addons/AudioPlaylist/src/presenter.js
> +                presenter.audio.playbackRate = presenter.playbackRate;
Logika zmiany playbackRate również powtarza się w metodach up/down, można spróbować ją wydzielić do osobnej metody

2022-05-23 14:39 UTC, Michal-sw-solwit submitted a review, later dismissed
Wszystko OK!

2022-06-09 08:20 UTC, msawoniuk reviewed
Proszę o odniesienie się do komentarza

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/src/presenter.js
> +        // createPlaybackRateSelectElement();
Niepotrzebny komentarz

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/src/presenter.js
> +            var playbackRateList = [0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0];
Widziałem, że już zmienione

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/src/presenter.js
> +            var percent = Math.round(volume * 100);
Widziałem, że już zmienione

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/src/presenter.js
> +                presenter.audio.playbackRate = presenter.playbackRate;
Widziałem, że już zmienione

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/src/presenter.js
> +            var percent = Math.round(volume * 100);
Widziałem, że już zmienione

2022-06-09 08:20 UTC, msawoniuk commented on addons/AudioPlaylist/test/KeyboardNavigationTests.js
> +      assertTrue(this.keyboardControllerObject !== null);
Złe wcięcie

2022-06-09 08:54 UTC, msawoniuk requested changes
Po rozmowie z Wojtkiem uznaliśmy, że przynajmniej dokumentacja powinna zostać poprawiona. Dlatego odrzucam.

2022-06-09 16:01 UTC, msawoniuk approved these changes
OK

2022-06-09 16:01 UTC, msawoniuk commented on addons/AudioPlaylist/documentation.md
> +                        <td>This property serves for uploading an audio file in ogg format into the module. It's needed for all common browsers.</td>
Czy ten fragment "It's needed for all common browsers." jest potrzebny ? 
Z dokumentacji dla Audio ten fragment usunąłeś.

2022-06-10 05:56 UTC, msawoniuk approved these changes
OK

2022-06-10 08:24 UTC, msawoniuk requested changes
Możliwe, że tego błędu nie zauważyłem podczas wcześniejszego sprawdzenia. 
Jeżeli ostatnim przyciskiem, na którym użyto spacji był przycisk zmiany głośności to nie da się aktywować przycisku odtwarzania/zatrzymania odtwarzania za pomocą spacji.
Przy innych guzikach tej blokady nie zauważyłem.

2022-06-13 09:11 UTC, Michal-sw-solwit submitted a review, later dismissed

2022-06-17 08:01 UTC, merged