feat(addon): Add TTS and KeyboardNavigation to addon TextColoring re #8402
icplayer/icplayer pull request #762
Opened 2022-05-17 09:19 UTC by karol-fischbach-solwit

Wersja testowa: xxx
Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/8402--tts--text-coloring/details#

2022-05-17 13:22 UTC, Michal-sw-solwit submitted a review, later dismissed
Oprócz Indentu wszystko OK!

2022-05-19 12:47 UTC, karol-fischbach-solwit commented on addons/Text_Coloring/src/addon.xml
> +            <property name="Selected" nameLabel="Text_Coloring_property_selected" type="staticrow">
Poprawione

2022-05-19 12:49 UTC, Michal-sw-solwit submitted a review, later dismissed

2022-05-24 06:26 UTC, wkarasSolwit submitted a review, later dismissed
OK

2022-06-01 09:14 UTC, Michal-sw-solwit approved these changes

2022-06-07 07:09 UTC, wkarasSolwit approved these changes
OK

2022-06-23 07:06 UTC, msawoniuk requested changes
Dodałem sugestię na przyszłość oraz powinny zostać dopisane testy.
Reszta ok

2022-06-23 10:06 UTC, msawoniuk approved these changes
Proponuję na testy nowe zadanie, aby nie blokować

2022-06-23 11:43 UTC, maciej-zawlocki-solwit approved these changes

2022-06-23 14:31 UTC, wkarasSolwit submitted a review, later dismissed
OK

2022-06-24 08:32 UTC, merged