Editing gap in Table while navigation is activated #8383
icplayer/icplayer pull request #767
Opened 2022-05-23 19:46 UTC by wkarasSolwit

[Zadanie](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8383)
[Wersja testowa](https://test-8383-dot-mauthor-dev.ew.r.appspot.com)
[Przykładowa lekcja](https://test-8383-dot-mauthor-dev.ew.r.appspot.com/embed/6269119110316032)

2022-05-24 13:53 UTC, karol-fischbach-solwit commented
- pusty plik Gradual_Show_Answer/test/EventSendingTest.js
- wersja testowa na firefox
![image](https://user-images.githubusercontent.com/75782376/170051693-e6f708c3-da03-4656-969d-9ff2c3e1f314.png)
- wersja testowa na chrome:
![image](https://user-images.githubusercontent.com/75782376/170051782-ef2db7d7-b9df-4067-8019-ff014be34b3a.png)

Czemu na wersji produkcyjnej (na testowej zresztą też) - https://www.mauthor.com/embed/5081113269239808 - nie mogę wejść w trybie naw. klawiaturowej (shift + enter)? Czy to część błędu w tym zadaniu?

2022-06-02 09:09 UTC, Michal-sw-solwit requested changes
Kod ok, ale warto dodać jakiś warunek, żeby nie wywalało tego błędu

2022-06-02 09:09 UTC, Michal-sw-solwit commented on addons/Table/src/presenter.js
> +        var gap = presenter.getGap(presenter.gapIndex)[0];
Ta linijka dalej wyrzuca exception w konsoli jeżeli w komórce jest zwykły tekst

2022-06-02 11:13 UTC, Michal-sw-solwit submitted a review, later dismissed

2022-06-03 08:17 UTC, merged