Added TTS support to FlashCards, re #8437
icplayer/icplayer pull request #789
Opened 2022-06-24 06:21 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8437
Wersja testowa: https://test-8437-dot-mauthor-dev.ew.r.appspot.com/embed/5444490036772864

2022-06-27 10:51 UTC, msawoniuk requested changes
Kod wymaga kilka poprawek (jak np. z duplikacją kodu).

Zauważyłem także, że klasa `keyboard_navigation_active_element` nie jest ustawiona na elemencie przy zmianie karty. W kodzie jedynie jest usuwana klasa przy zmianie karty. Natomiast przy używaniu kombinacji z Tab ten problem nie występuje.

Proponuję jeszcze testy przynajmniej na upgradeModel oraz setSpeechTexts.

Proszę także o poprawę nazwy commitu tak, aby oddawała rzecz jaka zostanie w commicie zrobiona (https://cbea.ms/git-commit/#imperative) czyli zmienić `Added` na `Add`

2022-06-27 10:51 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +    let KEYBOARD_NAVIGATION_ACTIVE_ITEM_CLASS = "keyboard_navigation_active_element";
biorąc pod uwagę ile razy korzystasz z nazw klas to proponuję, aby zdefiniować stałą CSS_CLASSES i tą także tam umieścić

2022-06-27 10:51 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +    presenter.keyboardController = function(keycode, isShift, event) {
czemu nie został wykorzystany KeyboardController ?

2022-06-27 10:51 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +            if (elementList[i].is("."+KEYBOARD_NAVIGATION_ACTIVE_ITEM_CLASS)) currentElementIndex = i;
Nie może być więcej elementów z tą samą klasą.
Po znalezieniu elementu powinno nastąpić wyjście z pętli.

2022-06-27 10:51 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +    }
brak średnika

2022-06-27 11:03 UTC, msawoniuk reviewed
Poproszę także o poprawę dokumentacji o nowe properties

2022-07-05 05:42 UTC, maciej-zawlocki-solwit commented on addons/FlashCards/src/presenter.js
> +	    return presenter.upgradeSpeechTexts(model);
Nie zgadzam się. W mojej opinii jedna funkcja na jedną "wersję" modelu jest czytelniejsza, lepiej oddaje to co się rzeczywiście dzieje. Zmienię natomiast nazwę, bo aktualna rzeczywiście może sugerować, że upgrade odnosi się do tylko do speech text'ów.

2022-07-05 05:48 UTC, maciej-zawlocki-solwit commented on addons/FlashCards/src/addon.xml
> +        <property name="langAttribute" displayName="Lang attribute" nameLabel="Connection_property_lang_attribute" type="string" />
Akurat to był błąd :) Kiedyś taka praktyka była, ale dawno od tego odeszliśmy na rzecz "indywidualnych" lang attribute. Widocznie "addon dawca" był jeszcze sprzed tej zmiany.

2022-07-05 07:20 UTC, maciej-zawlocki-solwit commented
> Kod wymaga kilka poprawek (jak np. z duplikacją kodu).
> 
> Zauważyłem także, że klasa `keyboard_navigation_active_element` nie jest ustawiona na elemencie przy zmianie karty. W kodzie jedynie jest usuwana klasa przy zmianie karty. Natomiast przy używaniu kombinacji z Tab ten problem nie występuje.
> 
> Proponuję jeszcze testy przynajmniej na upgradeModel oraz setSpeechTexts.
> 
> Proszę także o poprawę nazwy PR tak, aby oddawała rzecz jaka zostanie w commicie zrobiona (https://cbea.ms/git-commit/#imperative) czyli zmienić `Added` na `Add`

Odnośnie klasy, jest to działanie celowe, wzorowane na tym jak rozwiązane jest to w Text. W Text początkowo żaden element nie ma klasy keyboard_navigation_active_element, zostaje ona nadana dopiero w momencie przemieszczenia się po gapach za pomocą Tab/Shift+Tab. W związku z tym, w domyślnym stanie również nie ustawiam jej w Flash_cards, i pojawia się ona dopiero w momencie, gdy użytkownik zaczyna się przemieszczać po elementach addonu. W momencie przejścia na inną kartę/obrócenia karty nawigacja po prostu wraca do stanu domyślnego. keyboard_navigation_active_element jest ustawiane dla "całej karty" tylko w momencie, gdy po nawigowaniu po innych elementach użytkownik ponownie ją wybrał - ma to na celu dodatkowe zasygnalizowanie, co zostało wybrane, żeby użytkownik nie zastanawiał się, gdzie "zniknęło" zaznaczenie.

2022-07-06 08:19 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +	    return presenter.upgradeSpeechTexts(model);
Ok, też lubię to podejście. Najważniejsze, że nazwa metody się zmieniła

2022-07-06 08:37 UTC, msawoniuk requested changes
Zależy mi na tym aby pozbyć się duplikacji przy if.
Poprawa względem reszty komentarzy jest mile widziana + testy (na upgradeModel i setSpeechTexts)

2022-07-06 08:37 UTC, msawoniuk commented on addons/FlashCards/src/presenter.js
> +            if (currentElement.hasClass('flashcards-button-favourite')) {
powtórzenie z linią na dole

2022-07-06 08:37 UTC, msawoniuk commented on addons/FlashCards/documentation.md
> +        <td>A list of card items in which you define the front and back of each card.<br/>
poprawić wcięcia dla tego td

2022-07-06 08:37 UTC, msawoniuk commented on addons/FlashCards/documentation.md
> +
niepotrzebna pusta linia

2022-07-06 08:37 UTC, msawoniuk commented on addons/FlashCards/documentation.md
> +
niepotrzebna pusta linia

2022-07-06 08:37 UTC, msawoniuk commented on addons/FlashCards/documentation.md
> +
niepotrzebna pusta linia

2022-07-06 12:11 UTC, maciej-zawlocki-solwit commented on addons/FlashCards/documentation.md
> +        <td>A list of card items in which you define the front and back of each card.<br/>
td jest dzieckiem tr, wcięcie jest prawidłowe.

2022-07-07 07:15 UTC, wkarasSolwit submitted a review, later dismissed
OK

2022-07-07 07:15 UTC, wkarasSolwit commented on addons/FlashCards/src/presenter.js
> +            } else if (currentElement.hasClass('flashcards-card-audio-button')) {
sugeruję zamienienie pętli if / else if na konstrukcję switch() case

2022-07-07 07:19 UTC, msawoniuk submitted a review, later dismissed
OK

2022-07-07 07:19 UTC, msawoniuk commented on addons/FlashCards/documentation.md
> +        <td>A list of card items in which you define the front and back of each card.<br/>
rozchodziło mi się wcześniej o całe td, czyli od tej linijki do 20.

2022-07-08 08:40 UTC, merged