feat(addon): Added Keyboard Navigation + TTS to Hierarchical Table Of Contents re #8436
icplayer/icplayer pull request #790
Opened 2022-06-27 12:45 UTC by Michal-sw-solwit

[Ticket](https://app.assembla.com/spaces/lorepo/tickets/8436--tts--hierarchical-toc/details)
[Lekcja testowa](https://test-8436-dot-mauthor-dev.ew.r.appspot.com/embed/6221373015851008)

2022-06-28 10:20 UTC, msawoniuk requested changes
Poza niektórymi wymaganymi zmianami oraz kilkoma sugestiami w kodzie powinieneś jeszcze:
1. Dodać zmianę w changelog.txt
2. Poprawić dokumentację dla tego addonu o nowe properties `langAttribute` i `speechTexts`. Następnie dać do sprawdzenie Learneticowi (tak dla pewności). Dokumentacje także będzie trzeba poprawić na mautorze (ja zazwyczaj to robię po tym jak zadanie będzie miało status `Deployed`) i informuję o tym pod zadaniem. Aby to zrobić także będziesz potrzebował konta administratora lub możesz kogoś poprosić, aby to za Ciebie zrobił. Proponuję skopiować dokumentacje z produkcyjnego mauthora (zazwyczaj to ona jest najbardziej aktualna) i wkleić ją do `documentation.md` tego addonu.  PyCharm z ustawionym gitem pokaże różnice. `Demo presentation` pozostawić takie jakie jest u nas.
3. Jeżeli masz czas to warto napisać jeszcze testy pod TTS i nawigację. Te testy, które napisałeś to absolutne minimum. Ewentualnie jakby było mało czasu to poprosić kogoś z Learnetica, czy można napisać szczegółowe teksty w nowym zadaniu. Czym więcej będziesz pisać testów to łatwiej je będzie napisać ;). Wyjątkiem jest java, ja tam zawsze mam problemy :D

2022-06-28 13:21 UTC, Michal-sw-solwit commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        presenter.speechTexts = presenter.DEFAULT_TTS_PHRASES;
Tak, faktycznie, moje niedopatrzenie. Zamieniłem tę konstrukcję na skopiowanie

2022-06-28 14:41 UTC, Michal-sw-solwit commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        presenter.keyNavIndex--;
Faktycznie, stworzyłem ją, aby mieć dostęp do indeksu w presenterze (teraz widzę, że mogłem po prostu odwołać się do `presenter.keyboardControllerObject`. Zdecydowałem się przenieść metodę w której go potrzebowałem do prototypu kontrolera (`HTocKeyboardController.prototype.getNextSelectableElementIndexOrNull`)

2022-06-30 12:59 UTC, msawoniuk requested changes
Niektóre zmiany są konieczne.
Co do testów to nie wszędzie zaznaczałem niepotrzebne puste linie.
Ogólnie nie jest to wszędzie stosowane, ale od ułatwia czytanie testów.
Np. Łatwo sprawdzić czy nazwa testu się zgadza, gdy widoczne są podziały. Lub dostrzec czy jakiegoś testu nie brakuje. To podobnie jak z prefixem $ w celu odróżnienia elementów jQuerry od DOM. Polecam aby stosować

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        this.switchElement(1);
Jeżeli byłoby coś nie jasne to daj znać

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +            this.moveToPreviousKeyNavElement();
jak wyżej. Tutaj chyba też można byłoby od razu użyć `nextIndex` zamiast wykonywać ponownie metodę

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        const result = $(currentElement).hasClass("hier_report-header");
możesz od tego zrobić return
```suggestion
        return !$(currentElement).hasClass("hier_report-header");
```

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +            let $view = $(`<div></div>`);
złe wcięcie

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +            let $hierReport = $(`<div></div>`);
złe wcięcie

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +            const $table = $(`<table></table>`);
jw

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +    generateTableHeader: function () {
jw

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +    generateChapterWithID: function (id) {
jw

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +    generateTableRowWithIdAndParent: function (id, parentId) {
jw

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +    generateTableRowWithId: function (id) {
jw

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +        activateEnterEvent(this.presenter);
Jeżeli jest taka możliwość staraj się pisać testy tak, aby odpowiadały 3 krokom: GIVEN, WHEN, THEN a spacje je oddzielały:
```suggestion
        activateEnterEvent(this.presenter);
        this.setCollapsedChapterAsCurrentElement();

        activateTabEvent(this.presenter);

        assertTrue(hasKeyboardNavigationActiveElementClass(this.presenter.$view.find(".treegrid-4")));
```
Dla ułatwienia:
```suggestion
        \\ GIVEN
        activateEnterEvent(this.presenter);
        this.setCollapsedChapterAsCurrentElement();

        \\ WHEN
        activateTabEvent(this.presenter);

        \\ THEN
        assertTrue(hasKeyboardNavigationActiveElementClass(this.presenter.$view.find(".treegrid-4")));
```

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +        this.activateTTSWithoutReading(this.presenter);
To nie jest w pełni poprawnie zrobiony testy.
activateTTSWithoutReading ustawia keyboardNavigationActive na `true`.

Celem testu na pierwsze wejście jest sprawdzenie wejścia w addon (za pomocą klawiszu enter), gdy nawigacja klawiaturowa nie jest aktywna (np. keyboardNavigationActive jest na false, itd.).
To ze względu na funckjonalność `KeyboardController.prototype.enter`
Czyli w tym przypadku powinno być tylko ;)
```suggestion
        this.presenter.setWCAGStatus(true);
```

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +        const tableHeader = this.presenter.$view.find(".hier_report-header")
Przenieść do obszaru THEN i dziel spacją

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +
niepotrzebna pusta linia

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +
niepotrzebna pusta linia

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/KeyboardNavigationTests.js
> +
niepotrzebna pusta linia

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/test/UpgradeModelTests.js
> +                Title: this.presenter.DEFAULT_TTS_PHRASES.Title,
złe wcięcie

2022-06-30 12:59 UTC, msawoniuk commented on addons/Hierarchical_Table_Of_Contents/src/presenter.js
> +        presenter.speechTexts = presenter.DEFAULT_TTS_PHRASES;
Podoba mi się Twe nowe rozwiązanie

2022-07-07 06:50 UTC, maciej-zawlocki-solwit approved these changes

2022-07-08 08:41 UTC, merged