Add support for audio speed controller in keyboard navigation and TTS in Text Audio addon, re #8425
icplayer/icplayer pull request #791
Opened 2022-06-27 13:44 UTC by msawoniuk

Commit also includes:
* Update reading so that speech texts are no longer read with lang Atrrybute
* Change default texts of TTS
* Add support for enter button to read content
* Add support for exit button to stop audio

---------------------------------------------------------------------------------------------

[Link do zadania](https://learneticsa.assembla.com/spaces/lorepo/tickets/8425/details)
[Link do wersji testowej](https://test-8425-dot-mauthor-dev.ew.r.appspot.com/)
[Link do lekcji testowej](https://test-8425-dot-mauthor-dev.ew.r.appspot.com/embed/5154879049826304)

2022-06-29 11:51 UTC, wkarasSolwit requested changes
Wymagane poprawki w dokumentacji

2022-06-30 08:15 UTC, msawoniuk commented on addons/TextAudio/documentation.md
> +            This property serves for uploading an audio file in mp3 format into the module. It's needed for Internet Explorer.
Usunięte zostało "It's needed for Internet Explorer."

2022-06-30 08:15 UTC, msawoniuk commented on addons/TextAudio/documentation.md
> +            This property serves for uploading a vocabulary audio file in ogg format into the module. It's needed for all common browsers (exclude Internet Explorer and Safari).
Usunięte zostało "It's needed for all common browsers (exclude Internet Explorer and Safari)."

2022-06-30 10:33 UTC, wkarasSolwit approved these changes
OK

2022-07-01 08:00 UTC, merged