Add GSA functionality to Magic Boxes, re #8462
icplayer/icplayer pull request #808
Opened 2022-07-20 06:42 UTC by jedrzej-niemiera

Lekcja testowa:
https://test-8462-dot-mauthor-dev.ew.r.appspot.com/embed/5225627948941312

Ticket:
https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8462

2022-08-03 10:50 UTC, Michal-sw-solwit requested changes

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +            var numberOfLetters = 0;
można zamienić na let

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +
niepotrzebna pusta linia

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +            if (!presenter.GSAcorrectAnswerLocations.hasOwnProperty(key)) continue;
Ta linia jest chyba niepotrzebna - iterujesz po kluczach obiektu więc ten if nigdy się nie spełni

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +        var columns = presenter.configuration.columns;
można zamienić var na const, to samo można zrobić z innymi zmiennymi w tej funkcji i w showNextWord, które się nie zmieniają po inicjalizacji

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +                element = gridContainerWrapper.find(".selectable-element:eq(" + index + ")");
To można zamienić na interpolacje stringa 
```suggestion
                element = gridContainerWrapper.find(`.selectable-element:eq(${index}));
```

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +        if (presenter.configuration.checkByWords){
Początki funkcji showNextWord i showNextLetter są identyczne, aby uniknąć duplikacji kodu fajnie by było gdybyś zmodyfikował ten fragment, aby zawierał ten duplikowany kod np:
```suggestion
        for (let key in presenter.GSAcorrectAnswerLocations){
            if (usedGSAKeys.includes(key)) continue;
            else {
                presenter.configuration.checkByWords
                    ? presenter.showNextWord(key)
                    : presenter.showNextLetter(key);
            }
```

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +            if (!presenter.GSAcorrectAnswerLocations.hasOwnProperty(key)) continue;
Ta linia jest chyba niepotrzebna - iterujesz po kluczach obiektu więc ten if nigdy się nie spełni

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +                var element = gridContainerWrapper.find(".selectable-element:eq(" + index + ")");
To można zamienić na interpolacje stringa 
```suggestion
                const element = gridContainerWrapper.find(`.selectable-element:eq(${index}));
```

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +            if (GSALetterCounter == row.length) {
`==` można zmienić na `===`

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
niepotrzebna pusta linia

2022-08-03 10:50 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/test/EventTests.js
> +    'test showAnswers event calls the right method': function () {
Zmień proszę nazwy testów na konwencję given-when-then

2022-08-03 13:26 UTC, jedrzej-niemiera commented on addons/Magic_Boxes/src/presenter.js
> +        presenter.GSAcorrectAnswerLocations = {};
Zostawię tak jak jest. Tablica ma być z założenia analogiczna do presenter.answerWords, więc uważam że lepiej je również deklarować w tym samym miejscu

2022-08-03 13:40 UTC, Michal-sw-solwit commented on addons/Magic_Boxes/src/presenter.js
> +        presenter.GSAcorrectAnswerLocations = {};
W takim wypadku proponuję obie te zmienne wyrzucić na górę pliku. Wyczyści to funkcję presenterLogic z niepotrzebnych inicjalizacji

2022-08-03 14:17 UTC, jedrzej-niemiera commented on addons/Magic_Boxes/src/presenter.js
> +            if (!presenter.GSAcorrectAnswerLocations.hasOwnProperty(key)) continue;
Szczerze, znalazłem na stacku wersję z tym ifem. Wolę go zachować dla bezpieczeństwa

2022-08-03 14:36 UTC, jedrzej-niemiera commented on addons/Magic_Boxes/src/presenter.js
> +            if (!presenter.GSAcorrectAnswerLocations.hasOwnProperty(key)) continue;
Jak wyżej. Wolę go zostawić dla pewności

2022-08-09 11:03 UTC, Michal-sw-solwit approved these changes
Ok

2022-08-11 10:41 UTC, Michal-sw-solwit approved these changes

2022-08-11 10:42 UTC, merged