Add isNotActivity property to Puzzle
icplayer/icplayer pull request #819
Opened 2022-07-28 11:38 UTC by jedrzej-niemiera

Ticket:
https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=7832

Wersja testowa:
https://test-7832-dot-mauthor-dev.ew.r.appspot.com/

Lekcja testowa:
https://test-7832-dot-mauthor-dev.ew.r.appspot.com/embed/5808125321936896

2022-07-28 12:25 UTC, wkarasSolwit requested changes
do poprawy
Nowy parametr należy uwzględnić również w metodach:
- showAnswer
- getErrorCount
- setShowErrorsMode

2022-07-28 12:25 UTC, wkarasSolwit commented on addons/Puzzle/src/presenter.js
> +            upgradedModel['isNotActivity'] = false;
parametry typu boolean muszą być w formie String pisane z dużej litery: 'False' // 'True'

2022-07-28 12:25 UTC, wkarasSolwit commented on addons/Puzzle/src/presenter.js
> +    presenter.upgradeModel = function (model) {
metoda nie jest nigdzie wywołana

2022-07-29 06:18 UTC, jedrzej-niemiera commented on addons/Puzzle/src/presenter.js
> +            isNotActivity: !isActivity,
Poprawione

2022-07-29 06:19 UTC, jedrzej-niemiera commented on addons/Puzzle/src/presenter.js
> +            upgradedModel['isNotActivity'] = false;
Done

2022-07-29 07:12 UTC, jedrzej-niemiera commented on addons/Puzzle/src/presenter.js
> +    presenter.upgradeModel = function (model) {
Już jest

2022-08-01 10:09 UTC, Michal-sw-solwit submitted a review, later dismissed
Ok

2022-08-05 08:09 UTC, merged