Fix Table capturing events when hidden
icplayer/icplayer pull request #845
Opened 2022-09-07 16:50 UTC by jedrzej-niemiera

Ticket:
https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8506

Wersja testowa:
https://test-8506-dot-mauthor-dev.ew.r.appspot.com

Lekcja testowa:
https://test-8506-dot-mauthor-dev.ew.r.appspot.com/embed/5229178645381120

2022-09-08 09:31 UTC, Michal-sw-solwit submitted a review, later dismissed

2022-09-29 07:42 UTC, wkarasSolwit requested changes
kilka poprawek w kodzie
pobranie zmian z mastera

2022-09-29 07:42 UTC, wkarasSolwit commented on addons/Media_Recorder/src/presenter.js
> +            var _this2 = this;
proszę o zmianę nazwy: np. self, _this

2022-09-29 07:42 UTC, wkarasSolwit commented on addons/Table/src/presenter.js
>              presenter.showAnswers();
sugeruję zamienienie tych warunków na konstrukcję switch & case

2022-09-29 07:42 UTC, wkarasSolwit commented on addons/Table/src/presenter.js
> +            if (presenter.lastDraggedItem.value !== undefined && eventData.value == presenter.lastDraggedItem.value
sugeruję zmianę:
```
const isEqualToDraggedValue = presenter.lastDraggedItem.value && eventData.value === presenter.lastDraggedItem.value
const isEqualToDraggedItem = presenter.lastDraggedItem.item && eventData.item === presenter.lastDraggedItem.item

if (isEqualToDraggedValue  && isEqualToDraggedItem) {
       presenter.lastDraggedItem = {};
}
```

2022-09-29 07:42 UTC, wkarasSolwit commented on addons/crossword/src/presenter.js
> +    presenter.areUserAnswersSaved = false;
brakuje Ci zmian z dev-a - poprawki z crosswords są już wdrożone oraz changelog jest nieuzupełniony
i występuje konflikt dla zmian w addonie Table

2022-09-29 08:58 UTC, jedrzej-niemiera commented on addons/Media_Recorder/src/presenter.js
> +            var _this2 = this;
Zmiany w media recorderze nie są moje. Ponadto z tego co widzę, _this2 jest standardową konwencją nazywania takich zmiennych

2022-09-29 13:12 UTC, wkarasSolwit approved these changes
OK

2022-09-30 08:34 UTC, merged