fixed no break in tts at the end of a line, re #8560
icplayer/icplayer pull request #868
Opened 2022-10-27 09:18 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8560
Wersja testowa: https://test-8560-dot-mauthor-dev.ew.r.appspot.com/embed/6123104751321088

2022-10-27 16:09 UTC, msawoniuk requested changes
Ze względu na niejasność w pozostawieniu funkcji parseElement w kodzie to nie daję approve do czasu wyjaśnienia.

2022-10-27 16:09 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/WCAGUtils.java
> +	private static String parseElement(String html) {
Dlaczego zostawiłeś nieużywaną metodę i zmieniłeś jej nazwę ?

2022-10-28 06:21 UTC, msawoniuk submitted a review, later dismissed
OK

2022-11-08 18:07 UTC, msawoniuk requested changes
Nie są to zmiany konieczne jednak lepiej, aby zostały poprawione.
Co do działania nie mam zarzutu.

2022-11-14 10:10 UTC, maciej-zawlocki-solwit commented on src/main/java/com/lorepo/icplayer/client/module/text/WCAGUtils.java
> +					originalHTML = originalHTML + ".\u00A0";
Okazjonalnie zdarzały mi się problemy bez dodawania twardej spacji w tym miejscu. W trakcie odczytywania tekstu przez TTS nie powinno być różnicy między jedną a a dwiema spacjami obok siebie. W związku z tym wolę ją zostawić.

2022-11-14 10:21 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/WCAGUtils.java
> +					originalHTML = originalHTML + ".\u00A0";
Ok

2022-11-15 12:17 UTC, Michal-sw-solwit approved these changes

2022-11-17 14:55 UTC, msawoniuk reviewed
Wprowadzone rozwiązanie nie działa na wszystkie addony. Takim addonem jest addon Paragraph

2022-11-18 06:12 UTC, maciej-zawlocki-solwit commented on addons/Commons/src/tts-utils.js
> +                var trimmedText = text.replaceAll(self.statics.nonBreakingSpace, " ").replaceAll("&nbsp;", " ").trim();
&nbsp; to nie jest, w mojej opinii, magic number, nie jest niezrozumiała, ani w przyszłości nie będzie potrzeby modyfikowania takiej stałej na inną o tym samym znaczeniu. Uważam, że wrzucanie jej do self.statics tylko niepotrzebnie by go "napychało", zwłaszcza że jest tam już nonBreakingSpace.

2022-11-21 08:09 UTC, msawoniuk approved these changes

2022-11-25 10:55 UTC, merged