fix(addons): Fix TTS reading unnecessary comma in list elements
icplayer/icplayer pull request #872
Opened 2022-10-31 09:45 UTC by Michal-sw-solwit

[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/8545-tts---czytanie-comma-przy-li%C5%9Bcie-/details?comment=1702460047)
[Wersja testowa](https://test-8545-dot-mauthor-dev.ew.r.appspot.com)

2022-11-02 08:15 UTC, msawoniuk submitted a review, later dismissed

2022-11-09 08:15 UTC, msawoniuk requested changes
Rozwiązanie nie działa, gdy użyte twarde spacje na chrome. Może nie działać także z innymi białymi znakami

2022-11-09 08:15 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/WCAGUtils.java
> +		return text.replaceAll("\\\\alt\\{ \\|\\. \\}</li>", "\\\\alt{ |.}</li>");
Twój regex sprawdzić się tylko dla sytuacji ze spacją.
Jednak nie sprawdzi się z np. Twardą spacją lub innym białym znakiem.
Twarda spacja jest istotnym przypadkiem, gdyż klient po stworzeniu lekcji nie odróżni twardej spacji od zwykłej spacji.
Spójrz na: https://linuxhint.com/use-regex-whitespace-in-java/

2022-11-09 08:15 UTC, msawoniuk commented on addons/Commons/src/tts-utils.js
> +                replaceText = replaceText.replace(/\. $/, ".");
Twój regex nie sprawdzić się na sytuacje z jakimkolwiek białym znakiem. Wytłumaczenie poniżej.

2022-11-09 08:15 UTC, msawoniuk commented on src/main/java/com/lorepo/icplayer/client/module/text/WCAGUtils.java
> +		String regexPattern = "(?<!\\alt{ |\\.})</li>";
Jak wyżej

2022-11-17 07:35 UTC, maciej-zawlocki-solwit approved these changes

2022-11-22 09:40 UTC, wkarasSolwit submitted a review, later dismissed
OK

2022-11-25 10:58 UTC, merged