feat(addons): Add TTS to coloring addon re #8591
icplayer/icplayer pull request #896
Opened 2022-12-19 17:48 UTC by Michal-sw-solwit

[Ticket](https://app.assembla.com/spaces/lorepo/tickets/8591-wsparcie-tts-dla-coloringu/details)

2022-12-20 10:26 UTC, wkarasSolwit approved these changes
drobne poprawki stylistyczne:
- wcięcia
- nazewnictwo zmiennych
- utworzenie stałej dla defaultowego koloru na początku pliku

2022-12-20 10:26 UTC, wkarasSolwit commented on src/main/java/com/lorepo/icplayer/public/libs/dictionaries/fr/dictionary.js
> +	"Coloring_property_color": "Color",
wcięcia do poprawy

2022-12-28 10:31 UTC, msawoniuk requested changes
Inne błędy:
1. Po wpisaniu do property "Areas" "175;70;244 67 54 255, Head" (przecinek zamiast średnika). To wyskakuje błąd E02. Lepiej, aby był to błąd E03
2. Tab, Shift + Tab oraz strzałki prawo i lewo zabezpieczyłeś przed nawigacją w kółko elementów. Strzałki góra i dół nawigują w kółko. Możesz albo napisać funkcjonalność dla KeyboardControllera previousRow i nextRow lub nadpisać mapowanie jak np. w GradualShowAnswerKeyboardController.prototype.updateMapping. Dotyczy to zarówno nawigacji po obszarach jak i po menu kolorów.

2022-12-28 10:31 UTC, msawoniuk commented on addons/Coloring/documentation.md
> +            <p>Color RGBA - RGBA for the color</p>
Jeżeli zmienisz kolejność property to także zmień kolejność tutaj

2022-12-28 11:19 UTC, Michal-sw-solwit commented on addons/Coloring/src/presenter.js
> +    presenter.colorSpeechTextMap = {};
Ta mapa jest właśnie mapą speech textów kolorów. Zmieniłem za to nazwę funkcji która używa tej mapy z `getCurrentAreaColor `na `getCurrentAreaColorSpeechText`, aby bardziej nakreślić, że wyciągamy speech texty

2022-12-28 11:27 UTC, Michal-sw-solwit commented on addons/Coloring/src/addon.xml
> +                <property name="speechText" displayName="Description" nameLabel="Coloring_property_description" type="string" isLocalized="true"/>
Chodzi o property "speechText"? Nazwałem to w ten sposób, ponieważ TTS może działać zarówno na polach jak i kolorach. W ten sposób i pole i kolor posiadają property "speechText" i podczas czytania nie musimy rozrózniać czy działamy akurat z kolorem czy polem, tylko mamy jeden wspólny format. 
 
Zgadzam się, że w przypadku dodawania tekstu "colorName"  byłoby bardziej czytelne, ale z przyczyny ujednolicenia wolę zostawić tak jak jest

2022-12-28 11:30 UTC, Michal-sw-solwit commented on addons/Coloring/src/presenter.js
> +        if(!upgradedModel['showAllAnswersInGradualShowAnswersMode']) {
Przypadkowe powtórzenie :p

2022-12-28 12:30 UTC, msawoniuk commented on addons/Coloring/src/presenter.js
> +    presenter.colorSpeechTextMap = {};
👍

2022-12-28 12:30 UTC, msawoniuk commented on addons/Coloring/src/addon.xml
> +                <property name="speechText" displayName="Description" nameLabel="Coloring_property_description" type="string" isLocalized="true"/>
👍

2022-12-28 12:34 UTC, msawoniuk submitted a review, later dismissed

2023-01-03 08:27 UTC, msawoniuk requested changes
Jest kilka problemów na wersji testowej:
1. Jak napisała Agnieszka w punkcie 2 to "aby w nawigację klawiaturową (nie TTS) nie wchodził addon jeśli nie ma nic zdefiniowanego w Colors". Obecnie zarówno w trybie TTS jak i samej nawigacji klawiaturowej przy braku zdefiniowanych kolorów wchodzi do addonu ale nie przechodzi po punktach. Proszę Cię, abyś poprosił ją o doprecyzowanie (możesz wskazać obecną lekcję z prośbą czy o to jej chodziło i że to nie są pełne testy akceptacyjne). Dla mnie nie jest to blocker - kwestia odmiennych zdań (które wyszłyby podczas testów akceptacyjnych).
2. Po tym jak Agnieszka zdecydowała, że nie ma być domyślnego koloru dla Colors to konieczne jest inne podejście do tematu. Powinno być tak, że w przypadku, gdy jakiś kolor nie ma zdefiniowanego RGBA lub speechText to powinien wyskoczyć error message podczas walidacji modelu, że muszą być oba pola zdefiniowane. Obecnie jeżeli ktoś zdefiniował wartość RGBA oraz nie zdefiniował nazwy to w walidacja modelu na to pozwala. Jest to problematyczne, gdyż brzydko to wygląda (dla użytkownika końcowego jak uczeń będzie to oglądać jak błąd strony) oraz nawigacja się psuje (niby działa ale zawsze pokazuje, że ostatni element jest zaznaczony)
![image](https://user-images.githubusercontent.com/79645404/210252988-ec502b1f-c5ea-4c06-a927-21d0245d68b2.png).  Natomiast jak jest sama nazwa i nie ma RGBA to także pozwala na to walidacja, ale już w run nie ma tego koloru. Long story short: Lepiej nie pozwalać użytkownikowi na robienie błędów, bo potem będą tickety z pytaniem dlaczego coś nie działa (z powodu działań użytkownika). To blocker.

2023-01-03 08:27 UTC, msawoniuk commented on addons/Coloring/src/presenter.js
> +        emptyColorName: "Undefined"
Raczej tego TTS nie będzie, ale zaznaczam gdyby jednak zostało.
To TTS nie jest zdefiniowane w build.xml, słowniczkach ani w upgradeModel.

2023-01-03 15:54 UTC, msawoniuk approved these changes
Podczas testów znalazłem kolejny błąd. Jeżeli jest błędna konfiguracja -

2023-01-09 11:40 UTC, merged