fix(editor) loading subtitles preview in editor re #8713
icplayer/icplayer pull request #943
Opened 2023-03-23 12:19 UTC by wkarasSolwit

[Ticket](https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8713)
[Wersja testowa](https://test-8713-dot-mauthor-dev.ew.r.appspot.com)
[Przykładowa lekcja](https://test-8713-dot-mauthor-dev.ew.r.appspot.com/present/5676068998479872#11)

2023-03-24 09:41 UTC, maciej-zawlocki-solwit submitted a review, later dismissed

2023-03-31 07:32 UTC, msawoniuk commented on addons/TextAudio/src/presenter.js
> +    presenter.changeSlideFromDataAllPreview = function AddonTextAudio_changeSlideFromDataAll (slide_data) {
Należy poprawić nazwę funkcji - duplikat

2023-03-31 07:32 UTC, msawoniuk requested changes
Jedna szybka poprawka

2023-03-31 08:24 UTC, msawoniuk approved these changes
OK

2023-04-03 10:00 UTC, merged