Add missing modules in tts titles, re #8750
icplayer/icplayer pull request #981
Opened 2023-06-23 07:57 UTC by maciej-zawlocki-solwit

Ticket: https://learneticsa.assembla.com/spaces/lorepo/tickets/realtime_cardwall?ticket=8750
Wersja testowa: https://test-8750-dot-mauthor-dev.ew.r.appspot.com/

2023-06-23 08:31 UTC, wkarasSolwit requested changes
brak zmian w changelog.txt

2023-06-23 08:31 UTC, wkarasSolwit commented on src/main/java/com/lorepo/icplayer/client/module/button/ButtonModule.java
> +				buttonName = "next page";
w celu skrócenia metody można od razu zwrócić tekst, zamiast go przypisywać do zmiennej i potem zwrócić

2023-06-26 06:26 UTC, wkarasSolwit submitted a review, later dismissed
OK

2023-06-28 08:39 UTC, msawoniuk approved these changes

2023-06-29 09:02 UTC, merged